-- ════════════════════════════════════════════════════════════════════════════
--  supabase/tests/rpc_authorization_test.sql
--
--  Proves the SECURITY DEFINER lockdown (308000 / 314000 / 316000) and the
--  meeting engagement authorization (304000) hold against REAL role/JWT
--  simulation — not just against the catalog.
--
--  RUN: node scripts/qa/run-pgtap.mjs rpc_authorization
--
--  One transaction, ends in ROLLBACK.
--  FIXTURE NOTE: public.profiles.id is FK-constrained to auth.users(id), so
--  every fixture user is created in auth.users FIRST.
--
--  The job fixture comes from _fixtures/canonical_job.sql. This suite used to
--  INSERT it already-assigned with contractor_id preset — a shape production
--  never produces and nx_guard_dispatch_requires_funding refuses outright
--  (FUNDING_REQUIRED), which aborted the whole suite before any assertion ran.
--  It is now built the canonical way: created unassigned → the inspector
--  applies → funded through the authorized platform path → admin_dispatch_job
--  as the admin, which is what sets contractor_id and status='assigned'. That
--  is the same end state the assertions below always assumed, reached legally.
--
--  N1  anon cannot invoke nx_notify
--  N2  an authenticated user cannot invoke nx_notify (arbitrary recipient)
--  N3  content cannot bypass it — the wrapper is gone, the grant is gone
--  N4  legitimate trigger-driven notification still reaches the right recipient
--  N5  service_role can still notify
--  W1  wallet debit is unreachable by anon/authenticated
--  W2  the other revoked definer RPCs are unreachable
--  M1  a stranger cannot schedule a meeting on someone else's job
--  M2  a job party CAN, and the admin-host rule still bites
-- ════════════════════════════════════════════════════════════════════════════

BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap;
\i supabase/tests/_fixtures/canonical_job.sql
SELECT plan(9);

SET LOCAL client_min_messages TO NOTICE;

-- Fixed actor ids: the section bodies below are dollar-quoted, where psql does
-- NOT interpolate, so they are written out literally. The JOB id is generated by
-- the fixture and concatenated in with quote_literal where it is needed.
\set CL    'aa111111-1111-1111-1111-111111111111'
\set INSP  'aa222222-2222-2222-2222-222222222222'
\set ADM   'aa333333-3333-3333-3333-333333333333'
\set RANDO 'aa444444-4444-4444-4444-444444444444'

INSERT INTO auth.users (id, instance_id, aud, role, email, created_at, updated_at)
VALUES
  (:'CL',    '00000000-0000-0000-0000-000000000000','authenticated','authenticated','ra.client@test.nx',    now(),now()),
  (:'INSP',  '00000000-0000-0000-0000-000000000000','authenticated','authenticated','ra.inspector@test.nx', now(),now()),
  (:'ADM',   '00000000-0000-0000-0000-000000000000','authenticated','authenticated','ra.admin@test.nx',     now(),now()),
  (:'RANDO', '00000000-0000-0000-0000-000000000000','authenticated','authenticated','ra.random@test.nx',    now(),now());

INSERT INTO public.profiles (id, role, full_name, email, is_verified) VALUES
  (:'CL',   'client',   'Auth Test Client',   'ra.client@test.nx',    true),
  (:'INSP', 'inspector','Auth Test Inspector','ra.inspector@test.nx', true),
  (:'ADM',  'admin',    'Auth Test Admin',    'ra.admin@test.nx',     true),
  (:'RANDO','inspector','Random Rita',        'ra.random@test.nx',    true);

-- Canonical dispatch → status='assigned', contractor_id = INSP, funded.
SELECT nx_fx_dispatched_job(:'CL', :'INSP', :'ADM', 'RPC AUTH TEST') AS "JOB" \gset
UPDATE public.jobs SET description = 'suite' WHERE id = :'JOB';

-- ── N1 / N2 — nx_notify is off the public API ───────────────────────────────
SELECT lives_ok($$
do $n1$
BEGIN
  IF has_function_privilege('anon','public.nx_notify(uuid,text,text,text,text,uuid)','EXECUTE') THEN
    RAISE EXCEPTION 'N1 FAILED: anon can execute nx_notify';
  END IF;
END $n1$;
$$, 'N1 — anon cannot invoke nx_notify');

SELECT lives_ok($$
do $n2$
BEGIN
  IF has_function_privilege('authenticated','public.nx_notify(uuid,text,text,text,text,uuid)','EXECUTE') THEN
    RAISE EXCEPTION 'N2 FAILED: authenticated can execute nx_notify (arbitrary-recipient primitive)';
  END IF;
END $n2$;
$$, 'N2 — authenticated cannot invoke nx_notify');

-- N3 — actually attempt it as a logged-in stranger
SELECT lives_ok($$
do $n3$
DECLARE
  v_client uuid := 'aa111111-1111-1111-1111-111111111111';
  v_rando  uuid := 'aa444444-4444-4444-4444-444444444444';
  v_ok boolean; v_err text;
BEGIN
  PERFORM set_config('request.jwt.claims', json_build_object('sub', v_rando::text)::text, true);
  EXECUTE 'SET LOCAL ROLE authenticated';
  v_ok := false;
  BEGIN
    EXECUTE format(
      'SELECT public.nx_notify(%L, %L, %L, %L, NULL, NULL)',
      v_client, 'Your account is suspended', 'Click http://evil.example', 'system');
    v_ok := true;
  EXCEPTION WHEN OTHERS THEN v_err := SQLERRM;
  END;
  EXECUTE 'RESET ROLE';
  PERFORM set_config('request.jwt.claims', '', true);
  IF v_ok THEN
    RAISE EXCEPTION 'N3 FAILED: a stranger sent an arbitrary notification';
  END IF;
  RAISE NOTICE 'N3 — arbitrary notification refused (%)', left(v_err, 60);
END $n3$;
$$, 'N3 — a logged-in stranger cannot send an arbitrary notification');

-- ── N4 — the LEGITIMATE path still works: a moderation change must still
--         notify the job's client via trg_notify_jobs ────────────────────────
SELECT lives_ok($$
do $n4$
DECLARE
  v_client uuid := 'aa111111-1111-1111-1111-111111111111';
  v_job    uuid := $$ || quote_literal(:'JOB') || $$;
  v_before int; v_after int;
BEGIN
  SELECT count(*) INTO v_before FROM public.notifications WHERE recipient_id = v_client;
  UPDATE public.jobs SET moderation_status = 'approved', status = 'open'
   WHERE id = v_job AND moderation_status IS DISTINCT FROM 'approved';
  UPDATE public.jobs SET moderation_status = 'edits_requested' WHERE id = v_job;
  SELECT count(*) INTO v_after FROM public.notifications WHERE recipient_id = v_client;
  IF v_after <= v_before THEN
    RAISE EXCEPTION 'N4 FAILED: the trigger-driven notification path stopped working (% -> %)', v_before, v_after;
  END IF;
END $n4$;
$$, 'N4 — trigger-driven notification is still delivered to the client');

-- ── N5 — service_role retains access ────────────────────────────────────────
SELECT lives_ok($$
do $n5$
BEGIN
  IF NOT has_function_privilege('service_role','public.nx_notify(uuid,text,text,text,text,uuid)','EXECUTE') THEN
    RAISE EXCEPTION 'N5 FAILED: service_role lost nx_notify';
  END IF;
END $n5$;
$$, 'N5 — service_role can still notify');

-- ── W1 — the wallet debit primitive is unreachable ──────────────────────────
SELECT lives_ok($$
do $w1$
DECLARE
  v_client uuid := 'aa111111-1111-1111-1111-111111111111';
  v_rando  uuid := 'aa444444-4444-4444-4444-444444444444';
  v_ok boolean; v_err text;
BEGIN
  IF has_function_privilege('anon','public.debit_wallet_for_payout(uuid,bigint)','EXECUTE')
     OR has_function_privilege('authenticated','public.debit_wallet_for_payout(uuid,bigint)','EXECUTE') THEN
    RAISE EXCEPTION 'W1 FAILED: debit_wallet_for_payout is still publicly executable';
  END IF;
  PERFORM set_config('request.jwt.claims', json_build_object('sub', v_rando::text)::text, true);
  EXECUTE 'SET LOCAL ROLE authenticated';
  v_ok := false;
  BEGIN
    EXECUTE format('SELECT public.debit_wallet_for_payout(%L, 100000)', v_client);
    v_ok := true;
  EXCEPTION WHEN OTHERS THEN v_err := SQLERRM;
  END;
  EXECUTE 'RESET ROLE';
  PERFORM set_config('request.jwt.claims', '', true);
  IF v_ok THEN
    RAISE EXCEPTION 'W1 FAILED: a stranger drained another user''s wallet';
  END IF;
  RAISE NOTICE 'W1 — wallet debit refused (%)', left(v_err, 60);
END $w1$;
$$, 'W1 — wallet debit is unreachable by anon/authenticated');

-- ── W2 — every other revoked definer RPC ────────────────────────────────────
SELECT lives_ok($$
do $w2$
DECLARE v_sig text;
BEGIN
  FOREACH v_sig IN ARRAY ARRAY[
    'public.get_or_create_wallet(uuid)',
    'public.heal_contract_to_active(uuid)',
    'public.set_inspector_daily_limit(uuid,integer)',
    'public.create_system_notification(uuid,text,text,text,text,uuid)',
    'public.enqueue_notification(uuid,text,text,text,text,uuid,boolean,text,jsonb)',
    'public.generate_contract_for_job(uuid)',
    'public.recompute_reputation(uuid)',
    'public.mark_notification_email_sent(uuid,text)',
    'public.mark_notification_email_failed(uuid,text)',
    'public.notify_safe(uuid,text,text,text,text,uuid)',
    'public.nx_admin_upsert_direct_application(uuid,uuid,bigint)'
  ] LOOP
    BEGIN
      IF has_function_privilege('anon', v_sig, 'EXECUTE')
         OR has_function_privilege('authenticated', v_sig, 'EXECUTE') THEN
        RAISE EXCEPTION 'W2 FAILED: % is still publicly executable', v_sig;
      END IF;
    EXCEPTION WHEN undefined_function THEN
      RAISE NOTICE 'W2 skipped (not present): %', v_sig;
    END;
  END LOOP;
END $w2$;
$$, 'W2 — all revoked definer RPCs are off the public API');

-- ── M1 — meeting: a stranger cannot convene on someone else's job ───────────
SELECT lives_ok($$
do $m1$
DECLARE
  v_rando uuid := 'aa444444-4444-4444-4444-444444444444';
  v_job   uuid := $$ || quote_literal(:'JOB') || $$;
  v_ok boolean; v_err text;
BEGIN
  PERFORM set_config('request.jwt.claims', json_build_object('sub', v_rando::text)::text, true);
  v_ok := false;
  BEGIN
    PERFORM public.schedule_meeting('probe','https://example.com/x',
      now() + interval '1 hour', ARRAY[]::uuid[], v_job, NULL, 'other', 30);
    v_ok := true;
  EXCEPTION WHEN OTHERS THEN v_err := SQLERRM;
  END;
  IF v_ok THEN RAISE EXCEPTION 'M1 FAILED: a non-party scheduled a meeting'; END IF;
  IF v_err NOT LIKE 'not_authorized_for_this_job%' THEN
    RAISE EXCEPTION 'M1 FAILED: wrong rejection (%)', v_err;
  END IF;
END $m1$;
$$, 'M1 — a non-party cannot schedule a meeting on the job');

-- ── M2 — a party CAN, and client+inspector still needs an admin host ────────
SELECT lives_ok($$
do $m2$
DECLARE
  v_client uuid := 'aa111111-1111-1111-1111-111111111111';
  v_insp   uuid := 'aa222222-2222-2222-2222-222222222222';
  v_job    uuid := $$ || quote_literal(:'JOB') || $$;
  v_ok boolean; v_err text;
BEGIN
  PERFORM set_config('request.jwt.claims', json_build_object('sub', v_client::text)::text, true);
  PERFORM public.schedule_meeting('client solo','https://example.com/x',
    now() + interval '1 hour', ARRAY[]::uuid[], v_job, NULL, 'other', 30);

  v_ok := false;
  BEGIN
    PERFORM public.schedule_meeting('client+inspector','https://example.com/x',
      now() + interval '2 hour', ARRAY[v_insp]::uuid[], v_job, NULL, 'other', 30);
    v_ok := true;
  EXCEPTION WHEN OTHERS THEN v_err := SQLERRM;
  END;
  IF v_ok THEN
    RAISE EXCEPTION 'M2 FAILED: a client+inspector room was created without an admin host';
  END IF;
  IF v_err NOT LIKE 'admin_host_required%' THEN
    RAISE EXCEPTION 'M2 FAILED: wrong rejection for the anti-poaching rule (%)', v_err;
  END IF;
END $m2$;
$$, 'M2 — the job owner can convene; the admin-host anti-poaching rule holds');

SELECT * FROM finish();
ROLLBACK;
