// ════════════════════════════════════════════════════════════════════════════
//  app/inspector/contracts/job/[id]/page.tsx — Inspector signs a job contract
//
//  STRICT BLIND PRICING: this view CANNOT render client_price_cents.
//  Same view enforcement pattern as the client page.
// ════════════════════════════════════════════════════════════════════════════

import type { Metadata } from 'next';
import Link from 'next/link';
import { redirect } from 'next/navigation';
import {
  ArrowLeft,
  ShieldCheck,
  CheckCircle2,
  Clock,
  AlertCircle,
  ExternalLink,
  FileCheck2,
  Lock,
  HardHat,
} from 'lucide-react';
import { createSupabaseServerClient } from '@/lib/supabase/server';
import { fetchInspectorJobContract } from '@/lib/data/jobContracts';
import { inspectorSignJobContract } from '@/lib/actions/jobContracts';

export const metadata: Metadata = { title: 'Sign contract' };
export const dynamic = 'force-dynamic';

function fmtCents(v: number | null | undefined): string {
  if (v === null || v === undefined || !Number.isFinite(v)) return '—';
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 2,
  }).format(Number(v) / 100);
}

interface PageProps {
  params: Promise<{ id: string }>;
  searchParams?: Promise<{ error?: string; signed?: string }>;
}

export default async function InspectorJobContractPage({
  params,
  searchParams,
}: PageProps) {
  const { id } = await params;
  const sp = (await searchParams) ?? {};

  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    redirect(
      '/sign-in?next=' + encodeURIComponent(`/inspector/contracts/job/${id}`),
    );
  }

  const contract = await fetchInspectorJobContract(id);
  if (!contract) {
    return (
      <div className="rounded-3xl border border-accent-red/30 bg-accent-red/5 p-8 text-center">
        <AlertCircle className="mx-auto h-10 w-10 text-accent-red" strokeWidth={1.5} />
        <h1 className="mt-4 font-display text-xl font-semibold text-white">
          Contract not found
        </h1>
        <p className="mt-2 text-sm text-zinc-400">
          Either the contract id is wrong, or it&rsquo;s addressed to a
          different account.
        </p>
        <Link
          href="/inspector/contracts"
          className="mt-5 inline-flex items-center gap-1.5 rounded-full border border-white/10 bg-white/[0.03] px-4 py-2 text-xs font-semibold text-zinc-200 hover:border-violet/40 hover:text-white"
        >
          Back to contracts
        </Link>
      </div>
    );
  }

  const isClientSigned = !!contract.clientSignedAt;
  const isInspectorSigned = !!contract.inspectorSignedAt;
  const isFullyExecuted = contract.status === 'fully_executed';
  const isVoided = contract.status === 'voided';
  const isMyTurn =
    isClientSigned && !isInspectorSigned && !isVoided;

  return (
    <div className="space-y-6">
      <Link
        href="/inspector/contracts"
        className="inline-flex items-center gap-1.5 text-xs text-zinc-400 transition-colors hover:text-violet-glow"
      >
        <ArrowLeft className="h-3.5 w-3.5" strokeWidth={2} />
        Back to contracts
      </Link>

      <header>
        <p className="text-xs font-semibold uppercase tracking-industrial text-cyan-glow/80">
          Inspector Portal · Job contract
        </p>
        <h1 className="mt-2 font-display text-3xl font-semibold tracking-tight text-white sm:text-4xl">
          {contract.jobTitle ?? 'Inspection contract'}
        </h1>
        <p className="mt-2 text-sm text-zinc-400">
          Client:{' '}
          <span className="text-zinc-200">{contract.clientName ?? '—'}</span>
        </p>
      </header>

      {sp.signed && (
        <div className="rounded-2xl border border-accent-green/30 bg-accent-green/10 p-4 text-sm text-accent-green">
          ✅ Signed. The job is now in progress — open your assignments page.
        </div>
      )}
      {sp.error && (
        <div className="rounded-2xl border border-accent-red/30 bg-accent-red/10 p-4 text-sm text-accent-red">
          {decodeURIComponent(sp.error)}
        </div>
      )}

      {/* Status timeline */}
      <section className="rounded-3xl border border-white/[0.06] bg-white/[0.01] p-6">
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
          <StatusStep
            label="Generated by admin"
            ts={contract.createdAt}
            done
          />
          <StatusStep
            label="Client signs"
            ts={contract.clientSignedAt}
            done={isClientSigned}
            active={!isClientSigned && !isVoided}
          />
          <StatusStep
            label="You sign"
            ts={contract.inspectorSignedAt}
            done={isInspectorSigned}
            active={isMyTurn}
          />
        </div>
        {isFullyExecuted && (
          <div className="mt-4 rounded-xl border border-accent-green/30 bg-accent-green/10 p-3 text-sm text-accent-green">
            ✅ Fully executed. The job is in progress.
          </div>
        )}
        {isVoided && (
          <div className="mt-4 rounded-xl border border-accent-red/30 bg-accent-red/10 p-3 text-sm text-accent-red">
            ⚠ This contract was voided. Admin will issue a new one.
          </div>
        )}
      </section>

      {/* Payout — INSPECTOR VIEW ONLY */}
      <section className="rounded-3xl border border-cyan-glow/30 bg-gradient-to-br from-cyan-glow/[0.10] to-transparent p-6">
        <p className="inline-flex items-center gap-2 text-[10px] font-semibold uppercase tracking-industrial text-cyan-glow">
          <Lock className="h-3 w-3" strokeWidth={2} />
          Your payout · on signed report
        </p>
        <p className="mt-2 font-mono text-3xl font-semibold text-cyan-glow">
          {fmtCents(contract.inspectorPayoutCents)}
        </p>
        <p className="mt-1 text-xs text-zinc-400">
          Released to your Stripe Connect account after you and admin sign
          off on the final report. The client&rsquo;s budget is set
          separately by NEXPEC and is not visible to you.
        </p>
      </section>

      {/* Custom contract URL */}
      {contract.customContractUrl && (
        <a
          href={contract.customContractUrl}
          target="_blank"
          rel="noreferrer"
          className="inline-flex items-center gap-2 rounded-full border border-violet/30 bg-violet/10 px-4 py-2 text-xs font-semibold text-violet-glow hover:bg-violet/20"
        >
          Open uploaded contract document
          <ExternalLink className="h-3 w-3" strokeWidth={2} />
        </a>
      )}

      {/* Contract body */}
      {contract.contractTextMd && (
        <section className="rounded-3xl border border-white/[0.06] bg-white/[0.01] p-6 sm:p-8">
          <header className="mb-4 flex items-center gap-2">
            <FileCheck2 className="h-4 w-4 text-cyan-glow" strokeWidth={1.75} />
            <h2 className="font-display text-lg font-semibold tracking-tight text-white">
              Agreement
            </h2>
          </header>
          <pre className="max-h-[60vh] overflow-y-auto whitespace-pre-wrap break-words font-sans text-sm leading-relaxed text-zinc-300">
            {contract.contractTextMd}
          </pre>
        </section>
      )}

      {/* Sign form */}
      {isMyTurn && (
        <section className="rounded-3xl border border-cyan-glow/30 bg-cyan-glow/[0.05] p-6 sm:p-8">
          <h2 className="inline-flex items-center gap-2 font-display text-lg font-semibold tracking-tight text-white">
            <HardHat className="h-4 w-4 text-cyan-glow" strokeWidth={1.75} />
            Counter-sign &amp; accept the assignment
          </h2>
          <p className="mt-1 text-sm text-zinc-400">
            The client already signed. Your signature locks the assignment
            and flips the job to <span className="font-mono">in_progress</span>.
          </p>
          <form action={inspectorSignJobContract} className="mt-5 space-y-4">
            <input type="hidden" name="contractId" value={contract.id} />
            <label className="block">
              <span className="text-[10px] font-semibold uppercase tracking-industrial text-cyan-glow">
                Full legal name
              </span>
              <input
                type="text"
                name="typedName"
                required
                minLength={2}
                maxLength={160}
                placeholder="Alex Q. Public"
                className="mt-2 w-full rounded-xl border border-white/10 bg-white/[0.04] px-3 py-2.5 text-sm text-white placeholder:text-zinc-600 focus:border-cyan-glow/60 focus:bg-white/[0.06] focus:outline-none focus:ring-2 focus:ring-cyan-glow/30"
              />
            </label>
            <label className="group flex cursor-pointer items-start gap-3 rounded-xl border border-white/[0.06] bg-white/[0.02] p-4 transition-colors hover:border-cyan-glow/40 has-[:checked]:border-cyan-glow/40 has-[:checked]:bg-cyan-glow/10">
              <input
                type="checkbox"
                name="termsAccepted"
                value="on"
                required
                className="mt-0.5 h-4 w-4 shrink-0 rounded border-white/20 bg-transparent text-cyan-glow focus:ring-cyan-glow/40 focus:ring-offset-0"
              />
              <span className="flex-1 text-sm text-zinc-300">
                I agree to this Inspection Services Agreement, the{' '}
                <Link
                  href="/legal/terms"
                  target="_blank"
                  className="text-cyan-glow underline hover:text-white"
                >
                  NEXPEC Terms
                </Link>
                , and confirm my payout is held in escrow until the final
                report is signed off.
              </span>
            </label>
            <button
              type="submit"
              className="inline-flex items-center gap-2 rounded-full bg-cyan-glow px-6 py-2.5 text-sm font-semibold uppercase tracking-industrial text-ink-950 shadow-sm transition-colors hover:bg-cyan-glow/90"
            >
              <ShieldCheck className="h-4 w-4" strokeWidth={1.75} />
              Sign &amp; accept assignment
            </button>
            <p className="mt-2 inline-flex items-center gap-1.5 text-[11px] text-zinc-500">
              <Clock className="h-3 w-3" strokeWidth={1.75} />
              Your typed name + timestamp + IP + user-agent are recorded as
              an e-signature.
            </p>
          </form>
        </section>
      )}

      {!isClientSigned && !isVoided && (
        <section className="rounded-3xl border border-accent-amber/30 bg-accent-amber/10 p-6">
          <h2 className="inline-flex items-center gap-2 font-display text-base font-semibold text-accent-amber">
            <Clock className="h-4 w-4" strokeWidth={1.75} />
            Waiting on the client
          </h2>
          <p className="mt-1 text-sm text-zinc-300">
            The client needs to sign first. You&rsquo;ll get a notification
            the moment they do.
          </p>
        </section>
      )}
    </div>
  );
}

function StatusStep({
  label,
  ts,
  done,
  active,
}: {
  label: string;
  ts: string | null;
  done?: boolean;
  active?: boolean;
}) {
  return (
    <div
      className={
        'rounded-2xl border p-4 ' +
        (done
          ? 'border-accent-green/30 bg-accent-green/5'
          : active
            ? 'border-cyan-glow/40 bg-cyan-glow/10'
            : 'border-white/[0.06] bg-white/[0.01]')
      }
    >
      <div className="flex items-center gap-2">
        {done ? (
          <CheckCircle2 className="h-4 w-4 text-accent-green" strokeWidth={2} />
        ) : (
          <Clock
            className={
              'h-4 w-4 ' + (active ? 'text-cyan-glow' : 'text-zinc-500')
            }
            strokeWidth={1.75}
          />
        )}
        <p
          className={
            'text-[10px] font-semibold uppercase tracking-industrial ' +
            (done
              ? 'text-accent-green'
              : active
                ? 'text-cyan-glow'
                : 'text-zinc-500')
          }
        >
          {label}
        </p>
      </div>
      <p
        className={
          'mt-1.5 text-xs ' + (ts ? 'font-mono text-zinc-300' : 'text-zinc-600')
        }
      >
        {ts ? new Date(ts).toLocaleString() : 'Pending'}
      </p>
    </div>
  );
}
