[options]
exclude = [
  ".git",
  ".gitignore",
  ".DS_Store",
  "node_modules",
  "node_modules/*",
  "README.md",
  "README.md/*",
  "CHANGELOG.md",
  "CHANGELOG.md/*",
  "CONTRIBUTING.md",
  "CONTRIBUTING.md/*",
  "LICENSE",
  "LICENSE/*",
  "netlify.toml",
  "netlify.toml/*",
  "package.json",
  "package.json/*",
  "package-lock.json",
  "package-lock.json/*",
  "yarn.lock",
  "yarn.lock/*",
  "yarn-error.log",
  "yarn-error.log/*",
  "yarnrc.yml",
  "yarnrc.yml/*",
  "tsconfig.json",
  "tsconfig.json/*",
  "tsconfig.*.json",
  "tsconfig.*.json/*",
  "tsconfig.*.tsbuildinfo",
  "tsconfig.*.tsbuildinfo/*"
]