// ════════════════════════════════════════════════════════════════════════════
//  src/features/compliance/lib/working-copy-pdf.ts
//
//  TIER 2 — Client-Side "Working Copy" PDF share.
//
//  Companion to the Tier 1 canonical pipeline (generate-vca → Browserless →
//  signed PDF in storage). Tier 2 produces a LOCAL PDF on the user's device
//  by feeding the same affidavit HTML through expo-print, then hands it to
//  the native iOS/Android Share Sheet via expo-sharing.
//
//  TRUST POSTURE:
//    The local PDF is generated by the user's device. The bytes are NOT
//    covered by NEXPEC's Ed25519 signature, and the device's font set, CSS
//    rendering, and print pipeline are uncontrollable from our side. So
//    this artifact is explicitly labeled "WORKING COPY — NOT
//    CRYPTOGRAPHICALLY SIGNED" via:
//      1. A solid amber banner injected at the top of every page.
//      2. A diagonal "WORKING COPY" watermark on every page.
//      3. The @page top-center header on every printed page.
//    Tampering with the markers is possible but pointless — the regulator
//    grade artifact is the Tier 1 Signed PDF, downloadable from the public
//    verify page, anchored to verification_affidavits.pdf_sha256.
//
//  USAGE:
//    const result = await shareWorkingCopyPdf({
//      htmlSignedUrl: rowFromVerifyRpc.html_storage_signed_url,
//      fileName: `nexpec-working-copy-${verifyToken}.pdf`,
//    });
//    if (!result.ok) Alert.alert('Couldn't share', result.error ?? '...');
// ════════════════════════════════════════════════════════════════════════════

import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

// ─────────────────────────────────────────────────────────────
//  HTML injection — banner at the top of every page + page-wide
//  diagonal watermark + @page top-center header.
//
//  The banner is rendered with `position: fixed` so on print it
//  repeats at the top of each page (RN's print engine treats this
//  consistently across iOS / Android). The watermark uses
//  `body::before` with rotate to produce a centered diagonal mark.
// ─────────────────────────────────────────────────────────────
const WORKING_COPY_OVERLAY_CSS = `
<style>
  /* Diagonal watermark across the printable area. */
  body::before {
    content: "WORKING COPY";
    position: fixed;
    top: 38%;
    left: 0;
    right: 0;
    text-align: center;
    font-family: 'Inter', 'Helvetica Neue', Arial, sans-serif;
    font-size: 84pt;
    font-weight: 900;
    color: rgba(180, 83, 9, 0.10);
    transform: rotate(-28deg);
    pointer-events: none;
    z-index: 9998;
    letter-spacing: 6pt;
  }
  /* Per-page header band — printed at the top margin of each page. */
  @page {
    @top-center {
      content: "WORKING COPY — NOT CRYPTOGRAPHICALLY SIGNED";
      font-family: 'Inter', 'Helvetica Neue', Arial, sans-serif;
      font-size: 8pt;
      color: #B45309;
      font-weight: 700;
      letter-spacing: 1.2px;
    }
  }
  /* Banner at the very start of the first page (visible above the masthead). */
  .nx-working-copy-banner {
    background: #FBBF24;
    color: #1F2937;
    font-family: 'Inter', 'Helvetica Neue', Arial, sans-serif;
    font-size: 10pt;
    font-weight: 800;
    letter-spacing: 1.4pt;
    text-align: center;
    padding: 8pt 14pt;
    margin-bottom: 14pt;
    border: 1pt solid #B45309;
    border-radius: 3pt;
  }
</style>
`;

const WORKING_COPY_BANNER_HTML = `
<div class="nx-working-copy-banner">
  ⚠ WORKING COPY — NOT CRYPTOGRAPHICALLY SIGNED ⚠
</div>
`;

/**
 * Inject Working-Copy markers into the canonical affidavit HTML.
 * Safe-fall: if the HTML lacks </head> or <body>, falls back to a
 * prepend so the banner still renders.
 */
function injectWorkingCopyMarkers(html: string): string {
  let out = html;

  if (out.includes('</head>')) {
    out = out.replace('</head>', `${WORKING_COPY_OVERLAY_CSS}</head>`);
  } else {
    out = `${WORKING_COPY_OVERLAY_CSS}${out}`;
  }

  // Inject the banner right after the opening <body ...> tag.
  const bodyOpen = out.match(/<body[^>]*>/);
  if (bodyOpen) {
    out = out.replace(
      bodyOpen[0],
      `${bodyOpen[0]}${WORKING_COPY_BANNER_HTML}`,
    );
  } else {
    out = `${WORKING_COPY_BANNER_HTML}${out}`;
  }

  return out;
}

export interface WorkingCopyPdfOptions {
  /** Signed URL to the canonical HTML affidavit in the compliance bucket. */
  htmlSignedUrl: string;
  /**
   * Optional file-name hint surfaced to the share sheet on Android. iOS
   * derives its own name from the temp URI; this prop is only advisory.
   */
  fileName?: string;
  /**
   * If true, skip the share-sheet handoff and just return the local URI.
   * Useful for unit testing the pipeline.
   */
  skipShare?: boolean;
}

export interface WorkingCopyPdfResult {
  ok: boolean;
  /** Local file URI of the generated PDF (e.g. file:///.../Documents/print-xxx.pdf). */
  uri?: string;
  /** Human-readable failure reason. */
  error?: string;
}

/**
 * Generate a local "Working Copy" PDF from the canonical affidavit HTML
 * and hand it to the device's native share sheet. The original NEXPEC
 * signature is not extended to this artifact — see the file-level
 * comment for the trust posture.
 */
export async function shareWorkingCopyPdf(
  options: WorkingCopyPdfOptions,
): Promise<WorkingCopyPdfResult> {
  try {
    // 1) Fetch the canonical HTML from the bucket via the caller-provided
    //    signed URL. We never read from raw storage paths here — the verify
    //    page is anon, the inspector screen is authenticated; both have
    //    their own signed-URL minting policy.
    const resp = await fetch(options.htmlSignedUrl);
    if (!resp.ok) {
      return {
        ok: false,
        error: `Could not load affidavit HTML (HTTP ${resp.status}).`,
      };
    }
    const canonicalHtml = await resp.text();

    // 2) Inject the Working Copy banner + watermark + @page header.
    const stampedHtml = injectWorkingCopyMarkers(canonicalHtml);

    // 3) Render to a local PDF via the native print pipeline.
    //    base64=false keeps the bytes on disk so the share sheet can
    //    forward the file URI to other apps without re-encoding.
    const { uri } = await Print.printToFileAsync({
      html: stampedHtml,
      base64: false,
    });

    // 4) Hand off to the share sheet, unless caller requested raw URI only.
    if (!options.skipShare) {
      const sharingAvailable = await Sharing.isAvailableAsync();
      if (sharingAvailable) {
        await Sharing.shareAsync(uri, {
          dialogTitle: options.fileName ?? 'Share Working Copy PDF',
          mimeType: 'application/pdf',
          UTI: 'com.adobe.pdf',
        });
      } else {
        // Sharing not available on this device — return the URI so the
        // caller can surface a Toast with the path instead of failing.
        return {
          ok: true,
          uri,
          error: 'Share sheet not available on this device.',
        };
      }
    }

    return { ok: true, uri };
  } catch (e: any) {
    return {
      ok: false,
      error: e?.message ?? 'Failed to generate the working copy PDF.',
    };
  }
}
