-- ════════════════════════════════════════════════════════════════════════════
--  20260801590000_production_privilege_hotfix.sql
--
--  URGENT PRODUCTION SECURITY HOTFIX — standalone and dependency-minimal.
--
--  Designed to be applied to Production BY ITSELF, ahead of the rest of the
--  pending chain. It reads no table the chain creates, calls no function the
--  chain adds, and every grant it replays is guarded by to_regclass() /
--  to_regprocedure(), so objects that do not exist on this database yet are
--  skipped rather than raising. It is equally correct applied to Production as
--  it stands today, to Staging at HEAD, or to a fresh local reset.
--
--  ── THE EXPOSURE ───────────────────────────────────────────────────────────
--  anon is the UNAUTHENTICATED PostgREST role. Its key ships inside the public
--  web bundle and inside the mobile app, so "anon can" means "anyone can".
--
--    • anon held INSERT/UPDATE/DELETE/TRUNCATE on 281 tables. The tested
--      configuration grants it 4.
--    • On six of those tables RLS is not enabled at all, so nothing else stood
--      in the way: assets, badges, error_logs, form_drafts, spatial_ref_sys,
--      user_badges.
--    • Probed on a restored replica, as anon, inside a rolled-back transaction:
--        INSERT INTO badges          -> ACCEPTED
--        DELETE FROM form_drafts     -> ACCEPTED
--        INSERT INTO error_logs      -> refused only by a NOT NULL constraint,
--                                       i.e. it passed authorization
--    • anon also held SELECT on public.jobs, and authenticated held table-level
--      SELECT, which covers the buyer-only money columns GOLDEN_RULE_2 exists
--      to hide. anon read client_price_cents on 3 rows (max 300000 = $3,000.00);
--      an ordinary inspector read it on 6.
--
--  Measured against a database built only from this migration set at the same
--  HEAD: 2169 extra table privileges, 14392 extra column privileges, 2552 extra
--  function EXECUTE grants, and ZERO privileges missing. Production is a strict
--  SUPERSET, which is what makes this file safe — it cannot take away anything
--  the application relies on, because Staging serves the same web and mobile
--  builds on exactly the configuration replayed below.
--
--  ── WHY PRODUCTION AND NOTHING ELSE ────────────────────────────────────────
--  Production's history row for 00000000000000_remote_baseline.sql was
--  RECORDED, not executed — that is what a squash baseline is. The 122 REVOKE
--  statements inside it therefore never ran there, while every environment
--  rebuilt from the migration set did run them. The blanket
--  "GRANT ... ON ALL TABLES IN SCHEMA public TO anon, authenticated" from early
--  project setup was never withdrawn.
--
--  Applying the 45 pending migrations does NOT close this: the same probes
--  return the same numbers afterwards. That is why this is a hotfix and not a
--  line item in the promotion.
--
--  ── METHOD ─────────────────────────────────────────────────────────────────
--  Reset the two PostgREST roles and the PUBLIC pseudo-role they inherit from,
--  harden the default privileges so the drift cannot grow back, then replay the
--  tested configuration. Declarative and idempotent: applying it twice leaves
--  the same state, and it is a no-op on any environment already built from
--  these migrations.
--
--  service_role and postgres are not reset directly. They lose only what they
--  held via PUBLIC, which is precisely the tested configuration's posture.
-- ════════════════════════════════════════════════════════════════════════════

BEGIN;

-- ── 1. Reset the public-facing roles inside schema public ──────────────────
--  PUBLIC must be included: every role inherits it, so revoking from anon and
--  authenticated while leaving PUBLIC granted would be cosmetic.
REVOKE ALL ON ALL TABLES    IN SCHEMA public FROM anon, authenticated, PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated, PUBLIC;
REVOKE ALL ON ALL ROUTINES  IN SCHEMA public FROM anon, authenticated, PUBLIC;

-- ── 2. Stop the drift coming back ──────────────────────────────────────────
--  Revoking today's grants is not enough on its own. Production also carries
--  ALTER DEFAULT PRIVILEGES for role postgres granting anon arwdDxtm on every
--  TABLE, rwU on every SEQUENCE and EXECUTE on every FUNCTION created in schema
--  public from now on. Without this block the very next migration that creates
--  a table would hand it straight back to anon, and this reconciliation would
--  decay one object at a time.
--
--  The tested configuration keeps these defaults for postgres, authenticated
--  and service_role and omits anon; that is exactly what is reproduced here.
--  The supabase_admin-owned defaults are identical in both environments and are
--  not this role's to change.
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE ALL ON TABLES    FROM anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE ALL ON SEQUENCES FROM anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM anon;

-- ── 3. Replay the tested configuration ─────────────────────────────────────
--  ── Table-level grants: the tested configuration, verbatim ────────────
--  399 role/object pairs. to_regclass() skips anything the pending chain has
--  not created on this database yet, which is what makes this file applicable
--  to Production AS IT STANDS rather than only at HEAD.
DO $grants$
DECLARE r record;
BEGIN
  FOR r IN SELECT * FROM (VALUES
    ('anon','_app_config','SELECT'),
    ('anon','admin_direct_messages','SELECT'),
    ('anon','agreement_signatures','SELECT'),
    ('anon','agreements','SELECT'),
    ('anon','approval_decisions','SELECT'),
    ('anon','approval_policies','SELECT'),
    ('anon','approval_requests','SELECT'),
    ('anon','asset_defect_observations','SELECT'),
    ('anon','audit_events_public','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('anon','auth_recovery_codes','SELECT'),
    ('anon','bridge_documents','SELECT'),
    ('anon','bridge_slots','SELECT'),
    ('anon','client_assigned_inspector_view','SELECT'),
    ('anon','client_documents','SELECT'),
    ('anon','client_error_events','SELECT'),
    ('anon','client_inspector_shortlist_view','SELECT'),
    ('anon','client_job_contracts_view','SELECT'),
    ('anon','compliance_documents','SELECT'),
    ('anon','contact_submissions','SELECT'),
    ('anon','contractor_certifications','SELECT'),
    ('anon','contractors','SELECT'),
    ('anon','contracts','SELECT'),
    ('anon','conversations','SELECT'),
    ('anon','coordination_bridges','SELECT'),
    ('anon','country_codes','SELECT'),
    ('anon','courses','SELECT'),
    ('anon','deal_inspector_candidates','SELECT'),
    ('anon','deal_money_legs','SELECT'),
    ('anon','deal_nonconformances','SELECT'),
    ('anon','deal_payment_schedule','SELECT'),
    ('anon','deal_revision_events','SELECT'),
    ('anon','deal_revisions','SELECT'),
    ('anon','deals','SELECT'),
    ('anon','department_budgets','SELECT'),
    ('anon','department_members','SELECT'),
    ('anon','departments','SELECT'),
    ('anon','dispute_activities','SELECT'),
    ('anon','disputes','SELECT'),
    ('anon','doc_validations','SELECT'),
    ('anon','engineering_tools','SELECT'),
    ('anon','enterprise_domains','SELECT'),
    ('anon','escrow_logs','SELECT'),
    ('anon','expenses','SELECT'),
    ('anon','findings','SELECT'),
    ('anon','flash_report_attachments','SELECT'),
    ('anon','flash_reports','SELECT'),
    ('anon','fx_rates','SELECT'),
    ('anon','fx_refresh_runs','SELECT'),
    ('anon','geography_columns','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('anon','geometry_columns','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('anon','helpdesk_messages','SELECT'),
    ('anon','identity_links','SELECT'),
    ('anon','inspection_assets','SELECT'),
    ('anon','inspection_captures','SELECT'),
    ('anon','inspection_domains','SELECT'),
    ('anon','inspection_events','SELECT'),
    ('anon','inspection_evidence_requirements','SELECT'),
    ('anon','inspection_scope_templates','SELECT'),
    ('anon','inspection_seal_anchors','SELECT'),
    ('anon','inspector_certificates','SELECT'),
    ('anon','inspector_credentials','SELECT'),
    ('anon','inspector_domain_practice','SELECT'),
    ('anon','inspector_engagement_meta','SELECT'),
    ('anon','inspector_job_contracts_view','SELECT'),
    ('anon','inspectors_directory','SELECT'),
    ('anon','job_contracts','SELECT'),
    ('anon','job_meeting_participants','SELECT'),
    ('anon','job_meetings','SELECT'),
    ('anon','knowledge_base','SELECT'),
    ('anon','legal_document_acceptances','SELECT'),
    ('anon','legal_documents','SELECT'),
    ('anon','messages','SELECT'),
    ('anon','model_artifacts','SELECT'),
    ('anon','notification_logs','SELECT'),
    ('anon','notification_preferences','SELECT'),
    ('anon','notifications','SELECT'),
    ('anon','org_department_members','SELECT'),
    ('anon','org_departments','SELECT'),
    ('anon','org_invitations','SELECT'),
    ('anon','org_members','SELECT'),
    ('anon','organizations','SELECT'),
    ('anon','payments','SELECT'),
    ('anon','payout_requests','SELECT'),
    ('anon','pi_report_seals','SELECT'),
    ('anon','platform_settings','SELECT'),
    ('anon','preferred_inspectors','SELECT'),
    ('anon','profile_work_auth_documents','SELECT'),
    ('anon','profiles','SELECT'),
    ('anon','proposals','SELECT'),
    ('anon','public_demand_feed','SELECT'),
    ('anon','public_supply_feed','SELECT'),
    ('anon','push_tokens','SELECT'),
    ('anon','referrals','SELECT'),
    ('anon','report_reminders','SELECT'),
    ('anon','report_templates','SELECT'),
    ('anon','reports','SELECT'),
    ('anon','review_weights_config','SELECT'),
    ('anon','reviews','SELECT'),
    ('anon','reviews_public','SELECT'),
    ('anon','rfq_client_offers_view','SELECT'),
    ('anon','safety_checks','SELECT'),
    ('anon','saved_jobs','SELECT'),
    ('anon','signing_keys','SELECT'),
    ('anon','spatial_ref_sys','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('anon','stripe_webhook_events','SELECT'),
    ('anon','supplier_capability_catalog','SELECT'),
    ('anon','supplier_contracts','SELECT'),
    ('anon','supplier_directory','SELECT'),
    ('anon','supplier_profiles','SELECT'),
    ('anon','supplier_rfqs','SELECT'),
    ('anon','support_messages','SELECT'),
    ('anon','support_tickets','SELECT'),
    ('anon','tool_pro_grants','SELECT'),
    ('anon','tool_reference_data','SELECT'),
    ('anon','tool_runs','SELECT'),
    ('anon','trust_certificates','SELECT'),
    ('anon','unified_contracts_view','SELECT'),
    ('anon','user_course_progress','SELECT'),
    ('anon','user_roles','SELECT'),
    ('anon','vendor_contacts','SELECT'),
    ('anon','vendor_documents','SELECT'),
    ('anon','verification_affidavits','SELECT'),
    ('anon','verification_audit_log','SELECT'),
    ('anon','withdrawals','SELECT'),
    ('anon','work_sessions','SELECT'),
    ('authenticated','_app_config','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','activity_logs','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','admin_direct_conversations_view','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','admin_direct_messages','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','admin_direct_messages_view','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','admin_dispute_summary','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','admin_notification_settings','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','admin_operational_conversations_view','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','admin_operational_messages_view','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','agreement_signatures','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','agreements','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','ai_active_learning_scores','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','ai_analysis_queue','REFERENCES, TRIGGER, TRUNCATE'),
    ('authenticated','ai_audit_history','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','ai_correction_history','INSERT, SELECT'),
    ('authenticated','ai_dataset_images','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','ai_dataset_statistics','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','ai_dataset_versions','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','ai_detection_feedback','INSERT, SELECT'),
    ('authenticated','ai_detections','SELECT'),
    ('authenticated','ai_export_history','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','ai_golden_dataset_members','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','ai_golden_datasets','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','ai_hard_examples','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','ai_inference_statistics','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','ai_model_deployment_history','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','ai_monthly_snapshots','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','ai_prediction_history','INSERT, SELECT'),
    ('authenticated','ai_quality_statistics','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','ai_rare_classes','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','ai_rollback_history','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','ai_storage_providers','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','ai_storage_quotas','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','ai_sync_statistics','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','ai_training_runs','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','ai_training_snapshots','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','alerts','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','application_assignment_origin','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','applications','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','approval_decisions','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','approval_policies','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','approval_requests','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','asset_defect_observations','REFERENCES, SELECT, TRIGGER, TRUNCATE'),
    ('authenticated','assets','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','audit_events','INSERT, SELECT'),
    ('authenticated','audit_events_public','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','auth_recovery_codes','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','badges','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','bridge_documents','REFERENCES, SELECT, TRIGGER, TRUNCATE'),
    ('authenticated','bridge_slots','REFERENCES, SELECT, TRIGGER, TRUNCATE'),
    ('authenticated','certification_expiry_reminders','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','certification_stats','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','certifications','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','client_assigned_inspector_view','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','client_deal_view','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','client_delivery_policy','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','client_documents','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','client_error_events','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','client_inspector_shortlist_view','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','client_job_contracts_view','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','compliance_documents','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','consent_audit_logs','SELECT'),
    ('authenticated','consent_receipt_status','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','contact_submissions','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','contractor_certifications','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','contractors','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','contracts','REFERENCES, SELECT, TRIGGER, TRUNCATE'),
    ('authenticated','conversations','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','coordination_bridges','REFERENCES, SELECT, TRIGGER, TRUNCATE'),
    ('authenticated','country_codes','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','courses','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','deal_inspector_candidates','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','deal_money_legs','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','deal_nonconformances','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','deal_payment_schedule','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','deal_revision_events','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','deal_revisions','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','deals','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','department_budgets','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','department_members','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','departments','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','dev_sso_signup_check','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','dispute_activities','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','disputes','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','doc_validations','REFERENCES, SELECT, TRIGGER, TRUNCATE'),
    ('authenticated','documents','REFERENCES, SELECT, TRIGGER'),
    ('authenticated','engineering_tools','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','enterprise_domains','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','equipment','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','error_logs','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','escrow_logs','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','expenses','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','findings','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','flash_report_attachments','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','flash_reports','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','form_drafts','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','form_submissions','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','form_templates','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','funding_policy_audit','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','funding_term_defaults','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','fx_rates','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','fx_refresh_runs','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','geography_columns','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','geometry_columns','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','helpdesk_messages','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','identity_links','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','inspection_assets','REFERENCES, SELECT, TRIGGER, TRUNCATE'),
    ('authenticated','inspection_captures','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','inspection_domains','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','inspection_events','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','inspection_evidence_requirements','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','inspection_items','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','inspection_reports','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','inspection_scope_templates','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','inspection_seal_anchors','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','inspector_certificates','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','inspector_certifications','INSERT, SELECT, UPDATE'),
    ('authenticated','inspector_credentials','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','inspector_deal_view','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','inspector_documents','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','inspector_domain_practice','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','inspector_earnings','REFERENCES, SELECT, TRIGGER'),
    ('authenticated','inspector_engagement_meta','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','inspector_equipment','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','inspector_job_contracts_view','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','inspector_profile_smoke_test','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','inspector_skills','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','inspector_work_experience','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','inspectors_directory','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','integration_canonical_entities','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','integration_canonical_fields','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','integration_connector_health','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','integration_connectors','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','integration_dead_letter_queue','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','integration_entity_sync_state','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','integration_field_mappings','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','integration_inbound_messages','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','integration_mapping_versions','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','integration_record_history','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','integration_record_links','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','invoices','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','itp_point_results','SELECT'),
    ('authenticated','itp_points','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','job_applicant_identity_view','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','job_applications','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','job_contracts','REFERENCES, SELECT, TRIGGER, TRUNCATE'),
    ('authenticated','job_disputes','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','job_events','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','job_expenses','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','job_funding_stages','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','job_inspectors','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','job_meeting_participants','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','job_meetings','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','job_visit_assignments','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','job_visits','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','jobs','DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','jobs_client_view','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','jobs_inspector_secure_view','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','jobs_inspector_view','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','jobs_secure_view','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','knowledge_base','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','legal_consents','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','legal_document_acceptances','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','legal_documents','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','legal_templates','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','manual_payment_records','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','messages','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','milestones','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','model_artifacts','REFERENCES, SELECT, TRIGGER, TRUNCATE'),
    ('authenticated','notification_logs','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','notification_preferences','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','notification_settings','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','notifications','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','org_department_members','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','org_departments','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','org_invitations','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','org_members','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','org_scim_events','SELECT'),
    ('authenticated','org_scim_group_mappings','SELECT'),
    ('authenticated','org_scim_identities','SELECT'),
    ('authenticated','org_scim_membership_archive','SELECT'),
    ('authenticated','org_sso_connections','SELECT'),
    ('authenticated','org_sso_domains','SELECT'),
    ('authenticated','organizations','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','payment_audit_log','SELECT'),
    ('authenticated','payment_methods','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','payments','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','payout_advances','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','payout_requests','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','pi_report_seals','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','platform_settings','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','platform_wallet','SELECT'),
    ('authenticated','preferred_inspectors','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','profile_work_auth_documents','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','profiles','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','programs','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','project_documents','INSERT, SELECT'),
    ('authenticated','projects','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','proposals','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','public_demand_feed','SELECT'),
    ('authenticated','public_supply_feed','SELECT'),
    ('authenticated','push_token_history','SELECT'),
    ('authenticated','push_tokens','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','qcp_required_documents','SELECT'),
    ('authenticated','qcp_revisions','SELECT'),
    ('authenticated','qcp_stage_templates','SELECT'),
    ('authenticated','qcp_stages','SELECT'),
    ('authenticated','quality_control_plans','SELECT'),
    ('authenticated','reconciliation_runs','SELECT'),
    ('authenticated','referrals','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','report_reminders','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','report_review_history','SELECT'),
    ('authenticated','report_senior_reviews','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','report_templates','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','reports','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','review_weights_config','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','reviews','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','reviews_public','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','rfq_admin_quotes_view','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','rfq_client_offers_view','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','safety_checks','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','saved_jobs','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','secure_chat_profiles','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','signed_agreements','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','signing_keys','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','spatial_ref_sys','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','stripe_webhook_events','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','supplier_capability_catalog','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','supplier_contracts','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','supplier_deal_view','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','supplier_directory','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','supplier_earnings','SELECT'),
    ('authenticated','supplier_profiles','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','supplier_releases','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','supplier_rfqs','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','supplier_scorecard_confidence_bands','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','supplier_scorecard_metrics','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','supplier_scorecard_policy','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','support_messages','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','support_tickets','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','talent_candidate_domains','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','talent_candidate_profiles','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','talent_compliance_checks','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','talent_consents','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','talent_disclosures','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','talent_interviews','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','talent_offers','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','talent_opportunities','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','talent_opportunity_domains','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','talent_placements','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','talent_submission_employer_view','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','talent_submissions','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','tax_profiles','SELECT'),
    ('authenticated','tool_pro_grants','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','tool_reference_data','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','tool_runs','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','transactions','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','trust_certificates','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','unified_contracts_view','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','user_badges','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','user_course_progress','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','user_roles','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','v_certifications_with_status','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','v_cron_job_status','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','vendor_contacts','REFERENCES, SELECT, TRIGGER, TRUNCATE'),
    ('authenticated','vendor_documents','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','verification_affidavits','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','verification_audit_log','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','wallets','SELECT'),
    ('authenticated','withdrawal_requests','DELETE, INSERT, SELECT, UPDATE'),
    ('authenticated','withdrawals','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','work_experience','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','work_orders','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE'),
    ('authenticated','work_sessions','DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE')
  ) AS t(grantee, obj, privs) LOOP
    IF to_regclass('public.' || quote_ident(r.obj)) IS NOT NULL THEN
      EXECUTE format('GRANT %s ON TABLE public.%I TO %I', r.privs, r.obj, r.grantee);
    END IF;
  END LOOP;
END $grants$;

--  ── Column-level grants not implied by a table-level grant ────────────
DO $colgrants$
DECLARE r record;
BEGIN
  FOR r IN SELECT * FROM (VALUES
    ('anon','contact_submissions','INSERT','"channel", "email", "ip_address", "message", "name", "user_agent"'),
    ('authenticated','itp_point_results','UPDATE','"flash_report_id"'),
    ('authenticated','jobs','SELECT','"accepts_remote_inspectors", "admin_confirmed_at", "admin_confirmed_by", "agency_id", "applications_count", "budget_type", "calendar_event_id", "calendar_synced_at", "cancel_reason", "cancelled_at", "cancelled_by", "claimed_address_geocoded", "claimed_address_text", "client_id", "client_invoiced_at", "client_op_id", "client_settled_at", "contract_generated_at", "contract_id", "contractor_id", "created_at", "currency", "deleted_at", "department_id", "description", "domain", "escrow_status", "estimated_duration", "geog", "hired_inspector_id", "id", "identity_mode", "inspection_type", "inspector_id", "is_featured", "is_senior_review", "job_country", "job_type", "latitude", "location", "location_city", "longitude", "moderation_notes", "moderation_reviewed_at", "moderation_reviewed_by", "moderation_status", "payment_mode", "payout_marked_by", "payout_notes", "payout_paid_at", "payout_reference", "payout_status", "public_listable", "replacement_mode", "report_signed_docs_notes", "report_signed_docs_url", "report_template_id", "required_certifications", "requires_cci", "scheduled_date", "scope_template_id", "source_rfq_id", "specialty_slugs", "sponsorship_offered", "started_at", "status", "template_url", "title", "updated_at", "urgency"'),
    ('authenticated','org_scim_tokens','SELECT','"connection_id", "created_at", "created_by", "expires_at", "id", "last_used_at", "name", "org_id", "revoked_at", "revoked_by", "revoked_reason", "rotated_from_id", "scopes", "token_prefix"'),
    ('authenticated','supplier_quotes','INSERT','"quote", "rfq_id", "supplier_id"'),
    ('authenticated','supplier_quotes','SELECT','"created_at", "id", "presented_at", "quote", "rfq_id", "status", "supplier_id"'),
    ('authenticated','supplier_quotes','UPDATE','"quote"')
  ) AS t(grantee, obj, priv, cols) LOOP
    IF to_regclass('public.' || quote_ident(r.obj)) IS NOT NULL THEN
      EXECUTE format('GRANT %s (%s) ON TABLE public.%I TO %I', r.priv, r.cols, r.obj, r.grantee);
    END IF;
  END LOOP;
END $colgrants$;

--  ── Sequence USAGE ────────────────────────────────────────────────────
DO $seqgrants$
DECLARE r record;
BEGIN
  FOR r IN SELECT * FROM (VALUES
    ('anon','ai_audit_history_id_seq'),
    ('authenticated','ai_audit_history_id_seq')
  ) AS t(grantee, obj) LOOP
    IF to_regclass('public.' || quote_ident(r.obj)) IS NOT NULL THEN
      EXECUTE format('GRANT USAGE ON SEQUENCE public.%I TO %I', r.obj, r.grantee);
    END IF;
  END LOOP;
END $seqgrants$;

--  ── Function EXECUTE: blanket grant, then the tested exceptions ───────
--  A complement, because it is far smaller and therefore far easier to
--  review: 817 exceptions instead of ~3700 individual grants. Exact, because
--  Production's objects are a strict SUBSET of the tested configuration's
--  (verified: 0 Production-only functions, 0 Production-only tables), so
--  granting broadly and withdrawing the exceptions reproduces the tested
--  state precisely for every object that exists here.
--
--  Signatures are TYPE-ONLY (oidvectortypes). regprocedure does not accept
--  parameter names, so pg_get_function_identity_arguments cannot be used.
GRANT EXECUTE ON ALL ROUTINES IN SCHEMA public TO anon, authenticated, PUBLIC;
DO $fnrevoke$
DECLARE r record; v_oid oid;
BEGIN
  FOR r IN SELECT * FROM (VALUES
    ('anon','_actor_is_super_admin()'),
    ('anon','_compliance_actor_can_read(uuid)'),
    ('anon','accept_offer(uuid)'),
    ('anon','admin_accept_goods(uuid)'),
    ('anon','admin_assign_inspector(uuid, uuid, bigint, text)'),
    ('anon','admin_assign_inspector_directly(uuid, uuid, bigint, bigint, text)'),
    ('anon','admin_auto_match_inspector(uuid, bigint)'),
    ('anon','admin_cancel_job(uuid, text)'),
    ('anon','admin_counter_application(uuid, bigint, text)'),
    ('anon','admin_counter_revision(uuid, bigint, text)'),
    ('anon','admin_countersign_supplier_contract(uuid, text, text)'),
    ('anon','admin_decide_revision(uuid, text, text)'),
    ('anon','admin_decrypt_tax_id(uuid, text)'),
    ('anon','admin_dispatch_job(uuid, uuid, bigint, bigint, text)'),
    ('anon','admin_forward_application_to_client(uuid)'),
    ('anon','admin_fund_advance(uuid, text)'),
    ('anon','admin_generate_job_contract(uuid, bigint, bigint, text, text)'),
    ('anon','admin_generate_supplier_contract(uuid, text, text)'),
    ('anon','admin_invite_org_member(uuid, text, text)'),
    ('anon','admin_ledger_snapshot()'),
    ('anon','admin_list_internal_threads()'),
    ('anon','admin_list_listing_candidates()'),
    ('anon','admin_list_payout_requests(text)'),
    ('anon','admin_mark_goods_delivered(uuid)'),
    ('anon','admin_mark_payout_processed(uuid, text, text)'),
    ('anon','admin_mark_report_delivered(uuid)'),
    ('anon','admin_mark_withdrawal_paid(uuid, text)'),
    ('anon','admin_match_preview(uuid, integer)'),
    ('anon','admin_offer_inspector_shortlist(uuid, bigint, uuid[], integer)'),
    ('anon','admin_open_internal_thread(uuid)'),
    ('anon','admin_present_agreement(uuid)'),
    ('anon','admin_present_quote(uuid, bigint, text)'),
    ('anon','admin_recent_transactions(integer)'),
    ('anon','admin_record_manual_payment(uuid, text, bigint, text, date, text, text, text)'),
    ('anon','admin_reject_withdrawal(uuid, text)'),
    ('anon','admin_remove_org_member(uuid, text)'),
    ('anon','admin_replace_inspector(uuid, uuid, bigint, bigint, text)'),
    ('anon','admin_resolve_dispute(uuid, text, text)'),
    ('anon','admin_review_credential(uuid, text, text)'),
    ('anon','admin_review_job(uuid, text, text)'),
    ('anon','admin_review_job_with_pricing(uuid, text, text, bigint)'),
    ('anon','admin_search_assignable_inspectors(text, integer, boolean)'),
    ('anon','admin_set_fee_schedule(integer, integer, integer, integer, text)'),
    ('anon','admin_set_job_marketplace_visibility(uuid, boolean, text)'),
    ('anon','admin_set_job_pricing(uuid, bigint)'),
    ('anon','admin_set_listing_featured(uuid, text, boolean)'),
    ('anon','admin_set_marketplace_activation(uuid, boolean, text)'),
    ('anon','admin_set_project_policy(uuid, text, text)'),
    ('anon','admin_set_tax_exemption(uuid, boolean, text)'),
    ('anon','admin_set_tax_status(uuid, text)'),
    ('anon','admin_suspend_user(uuid, text)'),
    ('anon','admin_unsuspend_user(uuid)'),
    ('anon','admin_update_org_member_role(uuid, text)'),
    ('anon','admin_verify_user(uuid, text, text)'),
    ('anon','admin_void_contract(uuid, text)'),
    ('anon','ai_ops_create_monthly_snapshot(date)'),
    ('anon','apply_onboarding_role(text, text, text, text, text[], timestamp with time zone, text)'),
    ('anon','approve_inspection_report(uuid, boolean, text)'),
    ('anon','approve_job_and_pay(uuid, uuid, numeric)'),
    ('anon','assign_job_contractor(uuid, uuid)'),
    ('anon','bridge_send_invitation(uuid, text, text)'),
    ('anon','bridge_vendor_accept_schedule(text, uuid)'),
    ('anon','bridge_vendor_acknowledge_scope(text, uuid, jsonb)'),
    ('anon','bridge_vendor_counter_schedule(text, uuid, timestamp with time zone, text, text)'),
    ('anon','bridge_vendor_declare_site_access(text, uuid, jsonb)'),
    ('anon','bridge_vendor_get_state(text)'),
    ('anon','bridge_vendor_register_uploaded_document(text, uuid, text, text, text, bigint, text)'),
    ('anon','bridge_vendor_resolve_token(text)'),
    ('anon','bridge_vendor_sign_arrival(text, uuid, text, text)'),
    ('anon','bridge_vendor_touch(text)'),
    ('anon','bulk_update_inspector_specialties(uuid[], text[], text[])'),
    ('anon','can_review_job(uuid)'),
    ('anon','can_review_job(uuid, text)'),
    ('anon','cb_actor_profile(uuid)'),
    ('anon','cb_emit_audit(text, text, uuid, text, text, uuid, uuid, text, jsonb, jsonb)'),
    ('anon','cb_sha256_hex(text)'),
    ('anon','claim_ai_analysis_jobs(integer)'),
    ('anon','claim_stripe_webhook_event(text, text, jsonb)'),
    ('anon','clear_active_org()'),
    ('anon','client_sign_job_contract(uuid, text, text)'),
    ('anon','complete_ai_analysis_job(uuid)'),
    ('anon','complete_stripe_webhook_event(text)'),
    ('anon','create_organization(text, text)'),
    ('anon','create_system_notification(uuid, text, text, text, text, uuid)'),
    ('anon','credit_inspector_earning_on_approval(uuid)'),
    ('anon','credit_supplier_earnings(uuid, integer, text, uuid)'),
    ('anon','cron_kickoff_email_dispatch()'),
    ('anon','cron_kickoff_fx_refresh()'),
    ('anon','cron_upsert_fx_rate(text, text, numeric, date, text)'),
    ('anon','debit_wallet_for_payout(uuid, bigint)'),
    ('anon','discover_jobs(uuid, numeric, numeric, integer, text, integer, integer)'),
    ('anon','enqueue_notification(uuid, text, text, text, text, uuid, boolean, text, jsonb)'),
    ('anon','ensure_team_internal_conversation(uuid)'),
    ('anon','execute_auto_payout()'),
    ('anon','fin_visible_client_ids(uuid)'),
    ('anon','generate_contract_for_job(uuid)'),
    ('anon','get_budget_by_inspector(integer)'),
    ('anon','get_budget_monthly(integer)'),
    ('anon','get_budget_recent_activity(integer)'),
    ('anon','get_budget_summary()'),
    ('anon','get_marketplace_inspectors(text, numeric, boolean, boolean, text, text[], text, integer, integer)'),
    ('anon','get_or_create_wallet(uuid)'),
    ('anon','get_public_profile(uuid)'),
    ('anon','get_public_profiles(uuid[])'),
    ('anon','handle_job_cancellation()'),
    ('anon','handle_job_completion()'),
    ('anon','handle_new_user()'),
    ('anon','handle_new_user_wallet()'),
    ('anon','heal_contract_to_active(uuid)'),
    ('anon','hydrate_identity(text, jsonb)'),
    ('anon','increment_notification_badge()'),
    ('anon','inspector_sign_job_contract(uuid, text, text)'),
    ('anon','mark_direct_conversation_read(uuid)'),
    ('anon','mark_job_completed(uuid, text)'),
    ('anon','mark_notification_email_failed(uuid, text)'),
    ('anon','mark_notification_email_sent(uuid, text)'),
    ('anon','mark_operational_conversation_read(uuid)'),
    ('anon','moderate_review(uuid, text, text)'),
    ('anon','notify(uuid, text, text, text, text, uuid)'),
    ('anon','notify_safe(uuid, text, text, text, text, uuid)'),
    ('anon','nx_actor_is_platform()'),
    ('anon','nx_admin_assign_senior_reviewer(uuid, uuid)'),
    ('anon','nx_admin_deliver_report(uuid)'),
    ('anon','nx_admin_release_job_on_credit(uuid, integer, text)'),
    ('anon','nx_admin_report_first_pass_rate(timestamp with time zone, timestamp with time zone)'),
    ('anon','nx_admin_report_review_queue(integer, boolean)'),
    ('anon','nx_admin_review_inspection_report(uuid, text, boolean, text)'),
    ('anon','nx_admin_set_client_delivery_policy(uuid, text, integer, text)'),
    ('anon','nx_admin_set_funding_terms(uuid, jsonb)'),
    ('anon','nx_admin_upsert_direct_application(uuid, uuid, bigint)'),
    ('anon','nx_assert_online_payments_enabled()'),
    ('anon','nx_brokered_engagement_conflict(uuid, uuid)'),
    ('anon','nx_buyer_supplier_chat_authorized(uuid, uuid, uuid)'),
    ('anon','nx_buyer_supplier_conversation_authorized(uuid, uuid)'),
    ('anon','nx_buyer_supplier_related(uuid, uuid)'),
    ('anon','nx_can_access_doc(uuid, text, text)'),
    ('anon','nx_can_read_profile(uuid)'),
    ('anon','nx_can_record_visit_work(uuid, uuid)'),
    ('anon','nx_can_team_access_internal(uuid)'),
    ('anon','nx_can_team_manage_internal(uuid)'),
    ('anon','nx_can_view_supplier_scorecard(uuid, uuid)'),
    ('anon','nx_certification_expiry_scan(integer[])'),
    ('anon','nx_certification_flag_drift()'),
    ('anon','nx_certifications_verification_authority()'),
    ('anon','nx_client_may_read_report_doc(uuid, uuid)'),
    ('anon','nx_current_job_inspector_id(uuid)'),
    ('anon','nx_direct_chat_authorized(uuid, uuid, uuid)'),
    ('anon','nx_direct_conversation_authorized(uuid, uuid)'),
    ('anon','nx_email_verified(uuid)'),
    ('anon','nx_funding_delivery_satisfied(uuid)'),
    ('anon','nx_funding_ensure_schedule(uuid)'),
    ('anon','nx_funding_initial_satisfied(uuid)'),
    ('anon','nx_funding_invoice_status(uuid)'),
    ('anon','nx_funding_issue_delivery_invoice(uuid)'),
    ('anon','nx_funding_mark_stage_funded(uuid, text, text)'),
    ('anon','nx_funding_stage_is_funded(uuid, text)'),
    ('anon','nx_gate_report_doc_for_client(uuid, uuid)'),
    ('anon','nx_guard_dispatch_requires_contract()'),
    ('anon','nx_guard_dispatch_requires_funding()'),
    ('anon','nx_identity_replacement_reminders()'),
    ('anon','nx_inspector_job_match(uuid, uuid)'),
    ('anon','nx_inspector_job_match_core(uuid, uuid)'),
    ('anon','nx_integration_backoff_interval(integer, integer, integer, uuid)'),
    ('anon','nx_integration_bind_record(uuid, text, uuid)'),
    ('anon','nx_integration_can_administer(uuid)'),
    ('anon','nx_integration_claim_message(uuid, text, text, jsonb, text)'),
    ('anon','nx_integration_complete_message(uuid, jsonb, uuid)'),
    ('anon','nx_integration_fail_message(uuid, text, boolean, jsonb)'),
    ('anon','nx_integration_guard_link_org()'),
    ('anon','nx_integration_guard_mapping_target()'),
    ('anon','nx_integration_guard_message_org()'),
    ('anon','nx_integration_history_append_only()'),
    ('anon','nx_integration_is_service_context()'),
    ('anon','nx_integration_map_payload(uuid, text, jsonb)'),
    ('anon','nx_integration_process_message(uuid)'),
    ('anon','nx_integration_register_secret(uuid, text, text, text)'),
    ('anon','nx_integration_replay_message(uuid)'),
    ('anon','nx_integration_resolve_connector(text)'),
    ('anon','nx_integration_revoke_secret(uuid)'),
    ('anon','nx_integration_validate_canonical(text, jsonb)'),
    ('anon','nx_is_active_job_team_member(uuid, uuid)'),
    ('anon','nx_is_buyer_principal_side(uuid, uuid)'),
    ('anon','nx_is_current_job_inspector(uuid, uuid)'),
    ('anon','nx_is_eligible_senior_reviewer(uuid, uuid)'),
    ('anon','nx_is_inspector()'),
    ('anon','nx_is_job_buyer_finance_principal(uuid, uuid)'),
    ('anon','nx_is_job_buyer_side(uuid, uuid)'),
    ('anon','nx_is_job_supplier(uuid, uuid)'),
    ('anon','nx_is_org_identity_admin(uuid)'),
    ('anon','nx_is_org_member(uuid, uuid)'),
    ('anon','nx_is_report_contributor(uuid, uuid)'),
    ('anon','nx_is_strict_super_admin()'),
    ('anon','nx_itp_may_waive(uuid, uuid)'),
    ('anon','nx_itp_record_result(uuid, uuid, text, uuid, text, text)'),
    ('anon','nx_itp_release_hold(uuid, text)'),
    ('anon','nx_job_active_visit_for(uuid, uuid)'),
    ('anon','nx_job_add_inspector(uuid, uuid, text, text, boolean, text)'),
    ('anon','nx_job_add_visit(uuid, timestamp with time zone, timestamp with time zone, text, text, text, text, uuid)'),
    ('anon','nx_job_awaiting_replacement(uuid)'),
    ('anon','nx_job_broadcast_targets(uuid, integer, integer, integer)'),
    ('anon','nx_job_buyer_principal(uuid)'),
    ('anon','nx_job_cancel_visit(uuid, text)'),
    ('anon','nx_job_chat_counterparts(uuid)'),
    ('anon','nx_job_create_recurring_visits(uuid, timestamp with time zone, integer, integer, text, text, text)'),
    ('anon','nx_job_effective_identity_mode(uuid)'),
    ('anon','nx_job_inspector_team_public(uuid)'),
    ('anon','nx_job_inspectors(uuid)'),
    ('anon','nx_job_itp(uuid, uuid)'),
    ('anon','nx_job_itp_blocking_points(uuid, uuid)'),
    ('anon','nx_job_qcp(uuid)'),
    ('anon','nx_job_remove_inspector(uuid, uuid, text)'),
    ('anon','nx_job_replace_team_member(uuid, uuid, uuid, text)'),
    ('anon','nx_job_reschedule_visit(uuid, timestamp with time zone, timestamp with time zone, text)'),
    ('anon','nx_job_schedule_conflicts(uuid, uuid)'),
    ('anon','nx_job_set_lead(uuid, uuid)'),
    ('anon','nx_job_visits(uuid)'),
    ('anon','nx_mark_all_notifications_read()'),
    ('anon','nx_mark_notification_read(uuid)'),
    ('anon','nx_match_inspectors_for_job(uuid, integer, boolean)'),
    ('anon','nx_meeting_engagement_party(uuid, uuid, uuid)'),
    ('anon','nx_my_certification_status()'),
    ('anon','nx_my_chattable_suppliers()'),
    ('anon','nx_my_supplier_chat_targets()'),
    ('anon','nx_notify(uuid, text, text, text, text, uuid)'),
    ('anon','nx_notify_lifecycle(uuid, text, text, text, text, uuid)'),
    ('anon','nx_org_slug(text)'),
    ('anon','nx_program_rollup(uuid)'),
    ('anon','nx_project_qcp(uuid)'),
    ('anon','nx_qcp_accept_document(uuid, text)'),
    ('anon','nx_qcp_add_revision(uuid)'),
    ('anon','nx_qcp_approve_revision(uuid, text)'),
    ('anon','nx_qcp_attach_document(uuid, uuid)'),
    ('anon','nx_qcp_can_author(uuid, uuid)'),
    ('anon','nx_qcp_can_read(uuid, uuid)'),
    ('anon','nx_qcp_can_read_detail(uuid, uuid)'),
    ('anon','nx_qcp_create(uuid, text, uuid)'),
    ('anon','nx_qcp_effective_revision(uuid)'),
    ('anon','nx_qcp_for_job(uuid)'),
    ('anon','nx_qcp_is_engaged_inspector(uuid, uuid)'),
    ('anon','nx_qcp_may_accept_document(uuid, uuid)'),
    ('anon','nx_qcp_may_read(uuid, uuid)'),
    ('anon','nx_qcp_may_supply_document(uuid, uuid)'),
    ('anon','nx_qcp_org_author(uuid, uuid)'),
    ('anon','nx_qcp_org_reader(uuid, uuid)'),
    ('anon','nx_qcp_outstanding_requirements(uuid)'),
    ('anon','nx_qcp_revision_documents(uuid)'),
    ('anon','nx_qcp_revision_history(uuid)'),
    ('anon','nx_qcp_revoke_document_acceptance(uuid, text)'),
    ('anon','nx_qcp_rollup(uuid)'),
    ('anon','nx_qcp_scope_job_ids(uuid)'),
    ('anon','nx_qcp_scope_jobs(uuid, uuid)'),
    ('anon','nx_qcp_set_stage_templates(uuid, uuid[])'),
    ('anon','nx_qcp_stage_progress(uuid, uuid)'),
    ('anon','nx_qcp_submit_revision(uuid)'),
    ('anon','nx_qcp_visible(uuid, uuid)'),
    ('anon','nx_raise_ncr_from_inspection_item(uuid, text, text, text)'),
    ('anon','nx_raise_ncr_from_itp_point(uuid, text, text, text)'),
    ('anon','nx_report_contributors(uuid)'),
    ('anon','nx_report_itp_log(uuid)'),
    ('anon','nx_report_itp_rollup(uuid)'),
    ('anon','nx_report_qcp_rollup(uuid)'),
    ('anon','nx_report_resubmit(uuid, uuid, timestamp with time zone, text, text)'),
    ('anon','nx_report_review_stats(uuid)'),
    ('anon','nx_report_review_transition(text)'),
    ('anon','nx_report_visit_log(uuid)'),
    ('anon','nx_report_visit_rollup(uuid)'),
    ('anon','nx_schedule_conflicts_core(date, uuid, uuid, uuid)'),
    ('anon','nx_scim_deactivate_membership(uuid, uuid, uuid, text)'),
    ('anon','nx_scim_deprovision_user(text, text, text)'),
    ('anon','nx_scim_issue_token(uuid, text, uuid, integer, uuid, integer)'),
    ('anon','nx_scim_provision_user(text, text, uuid, boolean, text[], text)'),
    ('anon','nx_scim_redact_detail(jsonb)'),
    ('anon','nx_scim_resolve_role(uuid, text[])'),
    ('anon','nx_scim_resolve_token(text)'),
    ('anon','nx_scim_revoke_token(uuid, text)'),
    ('anon','nx_senior_review_decide(uuid, text, text, integer)'),
    ('anon','nx_stripe_settle_job(uuid, text, bigint, text, uuid)'),
    ('anon','nx_supplier_inspector_chat_authorized(uuid, uuid, uuid, uuid)'),
    ('anon','nx_supplier_inspector_conversation_authorized(uuid, uuid)'),
    ('anon','nx_supplier_scorecard(uuid)'),
    ('anon','nx_supplier_scorecard_band(integer)'),
    ('anon','nx_supplier_scorecard_counts(uuid, text)'),
    ('anon','nx_supplier_scorecard_evidence(uuid, text)'),
    ('anon','nx_supplier_scorecard_jobs(uuid)'),
    ('anon','nx_supplier_scorecard_metric(uuid, text)'),
    ('anon','nx_talent_admin_set_fee_status(uuid, text)'),
    ('anon','nx_talent_disclose_identity(uuid)'),
    ('anon','nx_talent_match_candidates(uuid, integer)'),
    ('anon','nx_talent_record_placement(uuid, uuid, integer)'),
    ('anon','nx_talent_revoke_disclosure(uuid)'),
    ('anon','nx_talent_submit_candidate(uuid, uuid)'),
    ('anon','nx_team_jobs()'),
    ('anon','nx_visit_assign_inspector(uuid, uuid, boolean)'),
    ('anon','nx_visit_evidence_summary(uuid)'),
    ('anon','nx_visit_job_id(uuid)'),
    ('anon','nx_visit_live_successor(uuid)'),
    ('anon','nx_visit_schedule_conflicts(uuid, uuid)'),
    ('anon','open_buyer_supplier_conversation(uuid, uuid)'),
    ('anon','open_direct_conversation(uuid, uuid)'),
    ('anon','open_supplier_inspector_conversation(uuid, uuid, uuid)'),
    ('anon','pi_record_ai_detection(uuid, text, text, numeric, text, integer, text, text, text, text[], boolean, jsonb, uuid, uuid, uuid)'),
    ('anon','pi_record_ai_feedback(uuid, uuid, text, integer, text, text, text, text, numeric, jsonb, uuid)'),
    ('anon','process_withdrawal(numeric, jsonb)'),
    ('anon','protect_certification_verification()'),
    ('anon','reassign_invoice_department(uuid, uuid, text)'),
    ('anon','recompute_reputation(uuid)'),
    ('anon','record_fx_refresh_result(uuid, boolean, integer, text, integer)'),
    ('anon','record_reconciliation_run(text, bigint)'),
    ('anon','refresh_public_demand_feed()'),
    ('anon','refresh_public_supply_feed()'),
    ('anon','release_ai_analysis_job(uuid, text)'),
    ('anon','release_stripe_webhook_event(text, text)'),
    ('anon','request_account_deletion()'),
    ('anon','request_senior_review(uuid)'),
    ('anon','request_withdrawal(bigint, text, text, uuid)'),
    ('anon','restore_wallet_balance(uuid, bigint, text)'),
    ('anon','schedule_meeting(text, text, timestamp with time zone, uuid[], uuid, uuid, text, integer)'),
    ('anon','seed_platform_owner(uuid)'),
    ('anon','send_message(uuid, text, text, text, text)'),
    ('anon','set_active_org(uuid)'),
    ('anon','set_inspector_daily_limit(uuid, integer)'),
    ('anon','settle_client_payment(uuid)'),
    ('anon','supplier_sign_contract(uuid, text, text)'),
    ('anon','tax_can_withdraw(uuid)'),
    ('anon','tax_is_verified(uuid)'),
    ('anon','tg_auto_issue_invoice_on_contract_executed()'),
    ('anon','tg_credit_inspector_on_confirm()'),
    ('anon','transfer_platform_owner(uuid, text)'),
    ('anon','update_average_rating()'),
    ('anon','update_average_rating_on_delete()'),
    ('anon','upsert_tax_profile(text, text, text, text, timestamp with time zone)'),
    ('anon','vault_store_tax_id(text, text, text, text)'),
    ('anon','vca_claimed_address_text(uuid)'),
    ('anon','wallet_credit_topup(uuid, bigint, text, uuid, uuid)'),
    ('authenticated','accept_offer(uuid)'),
    ('authenticated','approve_job_and_pay(uuid, uuid, numeric)'),
    ('authenticated','bridge_vendor_accept_schedule(text, uuid)'),
    ('authenticated','bridge_vendor_acknowledge_scope(text, uuid, jsonb)'),
    ('authenticated','bridge_vendor_counter_schedule(text, uuid, timestamp with time zone, text, text)'),
    ('authenticated','bridge_vendor_declare_site_access(text, uuid, jsonb)'),
    ('authenticated','bridge_vendor_get_state(text)'),
    ('authenticated','bridge_vendor_register_uploaded_document(text, uuid, text, text, text, bigint, text)'),
    ('authenticated','bridge_vendor_resolve_token(text)'),
    ('authenticated','bridge_vendor_sign_arrival(text, uuid, text, text)'),
    ('authenticated','bridge_vendor_touch(text)'),
    ('authenticated','cb_emit_audit(text, text, uuid, text, text, uuid, uuid, text, jsonb, jsonb)'),
    ('authenticated','claim_ai_analysis_jobs(integer)'),
    ('authenticated','claim_stripe_webhook_event(text, text, jsonb)'),
    ('authenticated','complete_ai_analysis_job(uuid)'),
    ('authenticated','complete_stripe_webhook_event(text)'),
    ('authenticated','create_system_notification(uuid, text, text, text, text, uuid)'),
    ('authenticated','cron_kickoff_email_dispatch()'),
    ('authenticated','cron_kickoff_fx_refresh()'),
    ('authenticated','cron_upsert_fx_rate(text, text, numeric, date, text)'),
    ('authenticated','debit_wallet_for_payout(uuid, bigint)'),
    ('authenticated','enqueue_notification(uuid, text, text, text, text, uuid, boolean, text, jsonb)'),
    ('authenticated','execute_auto_payout()'),
    ('authenticated','generate_contract_for_job(uuid)'),
    ('authenticated','get_or_create_wallet(uuid)'),
    ('authenticated','handle_job_cancellation()'),
    ('authenticated','handle_job_completion()'),
    ('authenticated','heal_contract_to_active(uuid)'),
    ('authenticated','mark_notification_email_failed(uuid, text)'),
    ('authenticated','mark_notification_email_sent(uuid, text)'),
    ('authenticated','notify_safe(uuid, text, text, text, text, uuid)'),
    ('authenticated','nx_admin_upsert_direct_application(uuid, uuid, bigint)'),
    ('authenticated','nx_can_access_doc(uuid, text, text)'),
    ('authenticated','nx_certification_expiry_scan(integer[])'),
    ('authenticated','nx_certification_flag_drift()'),
    ('authenticated','nx_inspector_job_match_core(uuid, uuid)'),
    ('authenticated','nx_integration_claim_message(uuid, text, text, jsonb, text)'),
    ('authenticated','nx_integration_complete_message(uuid, jsonb, uuid)'),
    ('authenticated','nx_integration_fail_message(uuid, text, boolean, jsonb)'),
    ('authenticated','nx_integration_process_message(uuid)'),
    ('authenticated','nx_integration_resolve_connector(text)'),
    ('authenticated','nx_job_broadcast_targets(uuid, integer, integer, integer)'),
    ('authenticated','nx_job_qcp(uuid)'),
    ('authenticated','nx_notify(uuid, text, text, text, text, uuid)'),
    ('authenticated','nx_notify_lifecycle(uuid, text, text, text, text, uuid)'),
    ('authenticated','nx_qcp_effective_revision(uuid)'),
    ('authenticated','nx_qcp_scope_job_ids(uuid)'),
    ('authenticated','nx_qcp_scope_jobs(uuid, uuid)'),
    ('authenticated','nx_schedule_conflicts_core(date, uuid, uuid, uuid)'),
    ('authenticated','nx_scim_deactivate_membership(uuid, uuid, uuid, text)'),
    ('authenticated','nx_scim_deprovision_user(text, text, text)'),
    ('authenticated','nx_scim_provision_user(text, text, uuid, boolean, text[], text)'),
    ('authenticated','nx_scim_resolve_token(text)'),
    ('authenticated','nx_stripe_settle_job(uuid, text, bigint, text, uuid)'),
    ('authenticated','nx_visit_job_id(uuid)'),
    ('authenticated','nx_visit_live_successor(uuid)'),
    ('authenticated','recompute_reputation(uuid)'),
    ('authenticated','record_fx_refresh_result(uuid, boolean, integer, text, integer)'),
    ('authenticated','release_ai_analysis_job(uuid, text)'),
    ('authenticated','release_stripe_webhook_event(text, text)'),
    ('authenticated','request_senior_review(uuid)'),
    ('authenticated','restore_wallet_balance(uuid, bigint, text)'),
    ('authenticated','seed_platform_owner(uuid)'),
    ('authenticated','set_inspector_daily_limit(uuid, integer)'),
    ('authenticated','stripe_settle_named_disclosure(uuid, text, bigint, uuid)'),
    ('authenticated','transfer_platform_owner(uuid, text)'),
    ('authenticated','vca_claimed_address_text(uuid)'),
    ('authenticated','wallet_credit_topup(uuid, bigint, text, uuid, uuid)'),
    ('public','_actor_is_super_admin()'),
    ('public','_app_config_get(text)'),
    ('public','_apply_revision(uuid, bigint, uuid)'),
    ('public','_brokered_create_engagement(uuid, uuid, bigint, text, text)'),
    ('public','_brokered_ensure_payment_schedule(uuid, bigint, text)'),
    ('public','_brokered_ensure_supplier_contract(uuid)'),
    ('public','_brokered_score_inspectors(uuid)'),
    ('public','_compliance_actor_can_read(uuid)'),
    ('public','_revision_log(uuid, uuid, text, text, bigint, text, text)'),
    ('public','_revision_notify(uuid, text, text, uuid)'),
    ('public','_tool_canon(jsonb)'),
    ('public','_tool_eval(jsonb, jsonb, integer)'),
    ('public','_tool_num(jsonb, jsonb, integer)'),
    ('public','accept_offer(uuid)'),
    ('public','admin_accept_goods(uuid)'),
    ('public','admin_assign_inspector(uuid, uuid, bigint, text)'),
    ('public','admin_assign_inspector_directly(uuid, uuid, bigint, bigint, text)'),
    ('public','admin_auto_match_inspector(uuid, bigint)'),
    ('public','admin_cancel_job(uuid, text)'),
    ('public','admin_counter_application(uuid, bigint, text)'),
    ('public','admin_counter_revision(uuid, bigint, text)'),
    ('public','admin_countersign_supplier_contract(uuid, text, text)'),
    ('public','admin_decide_revision(uuid, text, text)'),
    ('public','admin_decrypt_tax_id(uuid, text)'),
    ('public','admin_dispatch_job(uuid, uuid, bigint, bigint, text)'),
    ('public','admin_forward_application_to_client(uuid)'),
    ('public','admin_fund_advance(uuid, text)'),
    ('public','admin_generate_job_contract(uuid, bigint, bigint, text, text)'),
    ('public','admin_generate_supplier_contract(uuid, text, text)'),
    ('public','admin_invite_org_member(uuid, text, text)'),
    ('public','admin_ledger_snapshot()'),
    ('public','admin_list_internal_threads()'),
    ('public','admin_list_listing_candidates()'),
    ('public','admin_list_payout_requests(text)'),
    ('public','admin_mark_goods_delivered(uuid)'),
    ('public','admin_mark_payout_processed(uuid, text, text)'),
    ('public','admin_mark_report_delivered(uuid)'),
    ('public','admin_mark_withdrawal_paid(uuid, text)'),
    ('public','admin_match_preview(uuid, integer)'),
    ('public','admin_offer_inspector_shortlist(uuid, bigint, uuid[], integer)'),
    ('public','admin_open_internal_thread(uuid)'),
    ('public','admin_present_agreement(uuid)'),
    ('public','admin_present_quote(uuid, bigint, text)'),
    ('public','admin_recent_transactions(integer)'),
    ('public','admin_record_manual_payment(uuid, text, bigint, text, date, text, text, text)'),
    ('public','admin_reject_withdrawal(uuid, text)'),
    ('public','admin_remove_org_member(uuid, text)'),
    ('public','admin_replace_inspector(uuid, uuid, bigint, bigint, text)'),
    ('public','admin_resolve_dispute(uuid, text, text)'),
    ('public','admin_review_credential(uuid, text, text)'),
    ('public','admin_review_job(uuid, text, text)'),
    ('public','admin_review_job_with_pricing(uuid, text, text, bigint)'),
    ('public','admin_search_assignable_inspectors(text, integer, boolean)'),
    ('public','admin_set_fee_schedule(integer, integer, integer, integer, text)'),
    ('public','admin_set_job_marketplace_visibility(uuid, boolean, text)'),
    ('public','admin_set_job_pricing(uuid, bigint)'),
    ('public','admin_set_listing_featured(uuid, text, boolean)'),
    ('public','admin_set_marketplace_activation(uuid, boolean, text)'),
    ('public','admin_set_project_policy(uuid, text, text)'),
    ('public','admin_set_tax_exemption(uuid, boolean, text)'),
    ('public','admin_set_tax_status(uuid, text)'),
    ('public','admin_suspend_user(uuid, text)'),
    ('public','admin_unsuspend_user(uuid)'),
    ('public','admin_update_org_member_role(uuid, text)'),
    ('public','admin_verify_user(uuid, text, text)'),
    ('public','admin_void_contract(uuid, text)'),
    ('public','ai_ops_create_monthly_snapshot(date)'),
    ('public','apply_onboarding_role(text, text, text, text, text[], timestamp with time zone, text)'),
    ('public','approve_inspection_report(uuid, boolean, text)'),
    ('public','approve_job_and_pay(uuid, uuid, numeric)'),
    ('public','assign_job_contractor(uuid, uuid)'),
    ('public','audit_capture()'),
    ('public','award_and_dispatch(uuid)'),
    ('public','award_quote(uuid)'),
    ('public','bridge_send_invitation(uuid, text, text)'),
    ('public','bridge_vendor_accept_schedule(text, uuid)'),
    ('public','bridge_vendor_acknowledge_scope(text, uuid, jsonb)'),
    ('public','bridge_vendor_counter_schedule(text, uuid, timestamp with time zone, text, text)'),
    ('public','bridge_vendor_declare_site_access(text, uuid, jsonb)'),
    ('public','bridge_vendor_get_state(text)'),
    ('public','bridge_vendor_register_uploaded_document(text, uuid, text, text, text, bigint, text)'),
    ('public','bridge_vendor_resolve_token(text)'),
    ('public','bridge_vendor_sign_arrival(text, uuid, text, text)'),
    ('public','bridge_vendor_touch(text)'),
    ('public','bulk_update_inspector_specialties(uuid[], text[], text[])'),
    ('public','can_review_job(uuid)'),
    ('public','can_review_job(uuid, text)'),
    ('public','cancel_meeting(uuid)'),
    ('public','cb_actor_profile(uuid)'),
    ('public','cb_emit_audit(text, text, uuid, text, text, uuid, uuid, text, jsonb, jsonb)'),
    ('public','cb_sha256_hex(text)'),
    ('public','claim_ai_analysis_jobs(integer)'),
    ('public','claim_pending_notification_emails(integer)'),
    ('public','claim_stripe_webhook_event(text, text, jsonb)'),
    ('public','clear_active_org()'),
    ('public','client_review_engagement(uuid, text, text)'),
    ('public','client_select_inspector(uuid, uuid)'),
    ('public','client_sign_job_contract(uuid, text, text)'),
    ('public','complete_ai_analysis_job(uuid)'),
    ('public','complete_stripe_webhook_event(text)'),
    ('public','create_organization(text, text)'),
    ('public','create_rfq(text, jsonb, uuid, boolean, text)'),
    ('public','create_system_notification(uuid, text, text, text, text, uuid)'),
    ('public','credit_inspector_earning_on_approval(uuid)'),
    ('public','credit_supplier_earnings(uuid, integer, text, uuid)'),
    ('public','cron_kickoff_email_dispatch()'),
    ('public','cron_kickoff_fx_refresh()'),
    ('public','cron_upsert_fx_rate(text, text, numeric, date, text)'),
    ('public','debit_wallet_for_payout(uuid, bigint)'),
    ('public','delete_user()'),
    ('public','discover_jobs(uuid, numeric, numeric, integer, text, integer, integer)'),
    ('public','enqueue_notification(uuid, text, text, text, text, uuid, boolean, text, jsonb)'),
    ('public','ensure_team_internal_conversation(uuid)'),
    ('public','execute_auto_payout()'),
    ('public','fetch_department_spend_summary(uuid, text)'),
    ('public','fin_visible_client_ids(uuid)'),
    ('public','flag_job_dispute(uuid, text, text, text[])'),
    ('public','flash_report_add_attachment(uuid, text, text, text, bigint, text)'),
    ('public','flash_report_create(uuid, text, text, text, text, text, timestamp with time zone, uuid)'),
    ('public','flash_report_transition(uuid, text, text)'),
    ('public','fund_deal_balance(uuid)'),
    ('public','generate_contract_for_job(uuid)'),
    ('public','get_budget_by_inspector(integer)'),
    ('public','get_budget_monthly(integer)'),
    ('public','get_budget_recent_activity(integer)'),
    ('public','get_budget_summary()'),
    ('public','get_client_branding(uuid)'),
    ('public','get_inspector_reputation(uuid)'),
    ('public','get_marketplace_inspectors(text, numeric, boolean, boolean, text, text[], text, integer, integer)'),
    ('public','get_or_create_wallet(uuid)'),
    ('public','get_organization_members(uuid)'),
    ('public','get_overdue_reports()'),
    ('public','get_public_profile(uuid)'),
    ('public','get_public_profiles(uuid[])'),
    ('public','get_top_inspectors(integer, integer, numeric)'),
    ('public','handle_job_cancellation()'),
    ('public','handle_job_completion()'),
    ('public','handle_new_user()'),
    ('public','handle_new_user_wallet()'),
    ('public','heal_contract_to_active(uuid)'),
    ('public','hydrate_identity(text, jsonb)'),
    ('public','increment_notification_badge()'),
    ('public','inspector_assignment_end(uuid, uuid)'),
    ('public','inspector_sign_job_contract(uuid, text, text)'),
    ('public','inspectors_near_job(uuid, numeric, integer)'),
    ('public','is_active_contract_inspector(uuid, uuid)'),
    ('public','is_meeting_participant(uuid, uuid)'),
    ('public','job_applications_delete_trigger()'),
    ('public','job_applications_insert_trigger()'),
    ('public','job_applications_update_trigger()'),
    ('public','jobs_near_inspector(uuid, numeric, integer)'),
    ('public','list_my_sessions()'),
    ('public','mark_direct_conversation_read(uuid)'),
    ('public','mark_job_completed(uuid, text)'),
    ('public','mark_notification_email_failed(uuid, text)'),
    ('public','mark_notification_email_sent(uuid, text)'),
    ('public','mark_operational_conversation_read(uuid)'),
    ('public','ml_register_model(text, text, integer, text, text, bigint, text, text, text, text, text, text, text, text, text, text, jsonb, text)'),
    ('public','ml_resolve_models(text, text, text, text)'),
    ('public','ml_set_model_status(uuid, text)'),
    ('public','moderate_review(uuid, text, text)'),
    ('public','notify(uuid, text, text, text, text, uuid)'),
    ('public','notify_safe(uuid, text, text, text, text, uuid)'),
    ('public','nx_active_super_admin_count()'),
    ('public','nx_actor_is_platform()'),
    ('public','nx_admin_assign_senior_reviewer(uuid, uuid)'),
    ('public','nx_admin_deliver_report(uuid)'),
    ('public','nx_admin_release_job_on_credit(uuid, integer, text)'),
    ('public','nx_admin_report_first_pass_rate(timestamp with time zone, timestamp with time zone)'),
    ('public','nx_admin_report_review_queue(integer, boolean)'),
    ('public','nx_admin_review_inspection_report(uuid, text, boolean, text)'),
    ('public','nx_admin_set_client_delivery_policy(uuid, text, integer, text)'),
    ('public','nx_admin_set_funding_terms(uuid, jsonb)'),
    ('public','nx_admin_upsert_direct_application(uuid, uuid, bigint)'),
    ('public','nx_assert_online_payments_enabled()'),
    ('public','nx_auto_approve_due_engagements()'),
    ('public','nx_brokered_engagement_conflict(uuid, uuid)'),
    ('public','nx_buyer_supplier_chat_authorized(uuid, uuid, uuid)'),
    ('public','nx_buyer_supplier_conversation_authorized(uuid, uuid)'),
    ('public','nx_buyer_supplier_related(uuid, uuid)'),
    ('public','nx_can_access_doc(uuid, text, text)'),
    ('public','nx_can_read_profile(uuid)'),
    ('public','nx_can_record_visit_work(uuid, uuid)'),
    ('public','nx_can_team_access_conversation(uuid)'),
    ('public','nx_can_team_access_internal(uuid)'),
    ('public','nx_can_team_access_job(uuid)'),
    ('public','nx_can_team_manage_conversation(uuid)'),
    ('public','nx_can_team_manage_internal(uuid)'),
    ('public','nx_can_team_manage_job(uuid)'),
    ('public','nx_can_view_supplier_scorecard(uuid, uuid)'),
    ('public','nx_certification_expiry_scan(integer[])'),
    ('public','nx_certification_flag_drift()'),
    ('public','nx_certifications_verification_authority()'),
    ('public','nx_client_may_read_report_doc(uuid, uuid)'),
    ('public','nx_current_job_inspector_id(uuid)'),
    ('public','nx_direct_chat_authorized(uuid, uuid, uuid)'),
    ('public','nx_direct_conversation_authorized(uuid, uuid)'),
    ('public','nx_email_verified(uuid)'),
    ('public','nx_funding_delivery_satisfied(uuid)'),
    ('public','nx_funding_ensure_schedule(uuid)'),
    ('public','nx_funding_initial_satisfied(uuid)'),
    ('public','nx_funding_invoice_status(uuid)'),
    ('public','nx_funding_issue_delivery_invoice(uuid)'),
    ('public','nx_funding_mark_stage_funded(uuid, text, text)'),
    ('public','nx_funding_stage_is_funded(uuid, text)'),
    ('public','nx_gate_report_doc_for_client(uuid, uuid)'),
    ('public','nx_guard_dispatch_requires_contract()'),
    ('public','nx_guard_dispatch_requires_funding()'),
    ('public','nx_handle(uuid)'),
    ('public','nx_identity_replacement_reminders()'),
    ('public','nx_inspector_job_match(uuid, uuid)'),
    ('public','nx_inspector_job_match_core(uuid, uuid)'),
    ('public','nx_integration_backoff_interval(integer, integer, integer, uuid)'),
    ('public','nx_integration_bind_record(uuid, text, uuid)'),
    ('public','nx_integration_can_administer(uuid)'),
    ('public','nx_integration_claim_message(uuid, text, text, jsonb, text)'),
    ('public','nx_integration_complete_message(uuid, jsonb, uuid)'),
    ('public','nx_integration_fail_message(uuid, text, boolean, jsonb)'),
    ('public','nx_integration_guard_link_org()'),
    ('public','nx_integration_guard_mapping_target()'),
    ('public','nx_integration_guard_message_org()'),
    ('public','nx_integration_history_append_only()'),
    ('public','nx_integration_is_service_context()'),
    ('public','nx_integration_map_payload(uuid, text, jsonb)'),
    ('public','nx_integration_process_message(uuid)'),
    ('public','nx_integration_register_secret(uuid, text, text, text)'),
    ('public','nx_integration_replay_message(uuid)'),
    ('public','nx_integration_resolve_connector(text)'),
    ('public','nx_integration_revoke_secret(uuid)'),
    ('public','nx_integration_validate_canonical(text, jsonb)'),
    ('public','nx_is_active_job_team_member(uuid, uuid)'),
    ('public','nx_is_buyer_principal_side(uuid, uuid)'),
    ('public','nx_is_current_job_inspector(uuid, uuid)'),
    ('public','nx_is_eligible_senior_reviewer(uuid, uuid)'),
    ('public','nx_is_inspector()'),
    ('public','nx_is_job_buyer_finance_principal(uuid, uuid)'),
    ('public','nx_is_job_buyer_side(uuid, uuid)'),
    ('public','nx_is_job_supplier(uuid, uuid)'),
    ('public','nx_is_org_identity_admin(uuid)'),
    ('public','nx_is_org_member(uuid, uuid)'),
    ('public','nx_is_platform_owner(uuid)'),
    ('public','nx_is_report_contributor(uuid, uuid)'),
    ('public','nx_is_strict_super_admin()'),
    ('public','nx_itp_may_waive(uuid, uuid)'),
    ('public','nx_itp_record_result(uuid, uuid, text, uuid, text, text)'),
    ('public','nx_itp_release_hold(uuid, text)'),
    ('public','nx_job_active_visit_for(uuid, uuid)'),
    ('public','nx_job_add_inspector(uuid, uuid, text, text, boolean, text)'),
    ('public','nx_job_add_visit(uuid, timestamp with time zone, timestamp with time zone, text, text, text, text, uuid)'),
    ('public','nx_job_awaiting_replacement(uuid)'),
    ('public','nx_job_broadcast_targets(uuid, integer, integer, integer)'),
    ('public','nx_job_buyer_principal(uuid)'),
    ('public','nx_job_cancel_visit(uuid, text)'),
    ('public','nx_job_chat_counterparts(uuid)'),
    ('public','nx_job_create_recurring_visits(uuid, timestamp with time zone, integer, integer, text, text, text)'),
    ('public','nx_job_effective_identity_mode(uuid)'),
    ('public','nx_job_inspector_team_public(uuid)'),
    ('public','nx_job_inspectors(uuid)'),
    ('public','nx_job_itp(uuid, uuid)'),
    ('public','nx_job_itp_blocking_points(uuid, uuid)'),
    ('public','nx_job_qcp(uuid)'),
    ('public','nx_job_remove_inspector(uuid, uuid, text)'),
    ('public','nx_job_replace_team_member(uuid, uuid, uuid, text)'),
    ('public','nx_job_reschedule_visit(uuid, timestamp with time zone, timestamp with time zone, text)'),
    ('public','nx_job_schedule_conflicts(uuid, uuid)'),
    ('public','nx_job_set_lead(uuid, uuid)'),
    ('public','nx_job_visits(uuid)'),
    ('public','nx_mark_all_notifications_read()'),
    ('public','nx_mark_notification_read(uuid)'),
    ('public','nx_mask_name(text)'),
    ('public','nx_match_inspectors_for_job(uuid, integer, boolean)'),
    ('public','nx_meeting_engagement_party(uuid, uuid, uuid)'),
    ('public','nx_my_certification_status()'),
    ('public','nx_my_chattable_suppliers()'),
    ('public','nx_my_supplier_chat_targets()'),
    ('public','nx_notify(uuid, text, text, text, text, uuid)'),
    ('public','nx_notify_lifecycle(uuid, text, text, text, text, uuid)'),
    ('public','nx_online_payments_enabled()'),
    ('public','nx_org_slug(text)'),
    ('public','nx_program_rollup(uuid)'),
    ('public','nx_project_qcp(uuid)'),
    ('public','nx_qcp_accept_document(uuid, text)'),
    ('public','nx_qcp_add_revision(uuid)'),
    ('public','nx_qcp_approve_revision(uuid, text)'),
    ('public','nx_qcp_attach_document(uuid, uuid)'),
    ('public','nx_qcp_can_author(uuid, uuid)'),
    ('public','nx_qcp_can_read(uuid, uuid)'),
    ('public','nx_qcp_can_read_detail(uuid, uuid)'),
    ('public','nx_qcp_create(uuid, text, uuid)'),
    ('public','nx_qcp_effective_revision(uuid)'),
    ('public','nx_qcp_for_job(uuid)'),
    ('public','nx_qcp_is_engaged_inspector(uuid, uuid)'),
    ('public','nx_qcp_may_accept_document(uuid, uuid)'),
    ('public','nx_qcp_may_read(uuid, uuid)'),
    ('public','nx_qcp_may_supply_document(uuid, uuid)'),
    ('public','nx_qcp_org_author(uuid, uuid)'),
    ('public','nx_qcp_org_reader(uuid, uuid)'),
    ('public','nx_qcp_outstanding_requirements(uuid)'),
    ('public','nx_qcp_revision_documents(uuid)'),
    ('public','nx_qcp_revision_history(uuid)'),
    ('public','nx_qcp_revoke_document_acceptance(uuid, text)'),
    ('public','nx_qcp_rollup(uuid)'),
    ('public','nx_qcp_scope_job_ids(uuid)'),
    ('public','nx_qcp_scope_jobs(uuid, uuid)'),
    ('public','nx_qcp_set_stage_templates(uuid, uuid[])'),
    ('public','nx_qcp_stage_progress(uuid, uuid)'),
    ('public','nx_qcp_submit_revision(uuid)'),
    ('public','nx_qcp_visible(uuid, uuid)'),
    ('public','nx_raise_ncr_from_inspection_item(uuid, text, text, text)'),
    ('public','nx_raise_ncr_from_itp_point(uuid, text, text, text)'),
    ('public','nx_rate_band(bigint)'),
    ('public','nx_report_contributors(uuid)'),
    ('public','nx_report_itp_log(uuid)'),
    ('public','nx_report_itp_rollup(uuid)'),
    ('public','nx_report_qcp_rollup(uuid)'),
    ('public','nx_report_resubmit(uuid, uuid, timestamp with time zone, text, text)'),
    ('public','nx_report_review_stats(uuid)'),
    ('public','nx_report_review_transition(text)'),
    ('public','nx_report_visit_log(uuid)'),
    ('public','nx_report_visit_rollup(uuid)'),
    ('public','nx_schedule_conflicts_core(date, uuid, uuid, uuid)'),
    ('public','nx_scim_deactivate_membership(uuid, uuid, uuid, text)'),
    ('public','nx_scim_deprovision_user(text, text, text)'),
    ('public','nx_scim_issue_token(uuid, text, uuid, integer, uuid, integer)'),
    ('public','nx_scim_provision_user(text, text, uuid, boolean, text[], text)'),
    ('public','nx_scim_redact_detail(jsonb)'),
    ('public','nx_scim_resolve_role(uuid, text[])'),
    ('public','nx_scim_resolve_token(text)'),
    ('public','nx_scim_revoke_token(uuid, text)'),
    ('public','nx_senior_review_decide(uuid, text, text, integer)'),
    ('public','nx_stripe_settle_job(uuid, text, bigint, text, uuid)'),
    ('public','nx_supplier_inspector_chat_authorized(uuid, uuid, uuid, uuid)'),
    ('public','nx_supplier_inspector_conversation_authorized(uuid, uuid)'),
    ('public','nx_supplier_scorecard(uuid)'),
    ('public','nx_supplier_scorecard_band(integer)'),
    ('public','nx_supplier_scorecard_counts(uuid, text)'),
    ('public','nx_supplier_scorecard_evidence(uuid, text)'),
    ('public','nx_supplier_scorecard_jobs(uuid)'),
    ('public','nx_supplier_scorecard_metric(uuid, text)'),
    ('public','nx_talent_admin_set_fee_status(uuid, text)'),
    ('public','nx_talent_disclose_identity(uuid)'),
    ('public','nx_talent_match_candidates(uuid, integer)'),
    ('public','nx_talent_record_placement(uuid, uuid, integer)'),
    ('public','nx_talent_revoke_disclosure(uuid)'),
    ('public','nx_talent_submit_candidate(uuid, uuid)'),
    ('public','nx_team_jobs()'),
    ('public','nx_visit_assign_inspector(uuid, uuid, boolean)'),
    ('public','nx_visit_evidence_summary(uuid)'),
    ('public','nx_visit_job_id(uuid)'),
    ('public','nx_visit_live_successor(uuid)'),
    ('public','nx_visit_schedule_conflicts(uuid, uuid)'),
    ('public','open_buyer_supplier_conversation(uuid, uuid)'),
    ('public','open_direct_conversation(uuid, uuid)'),
    ('public','open_supplier_inspector_conversation(uuid, uuid, uuid)'),
    ('public','pi_record_ai_detection(uuid, text, text, numeric, text, integer, text, text, text, text[], boolean, jsonb, uuid, uuid, uuid)'),
    ('public','pi_record_ai_feedback(uuid, uuid, text, integer, text, text, text, text, numeric, jsonb, uuid)'),
    ('public','process_withdrawal(numeric, jsonb)'),
    ('public','protect_certification_verification()'),
    ('public','raise_nonconformance(uuid, text, text, text, text)'),
    ('public','reassign_invoice_department(uuid, uuid, text)'),
    ('public','recompute_reputation(uuid)'),
    ('public','record_fx_refresh_result(uuid, boolean, integer, text, integer)'),
    ('public','record_reconciliation_run(text, bigint)'),
    ('public','refresh_inspector_reputation()'),
    ('public','refresh_public_demand_feed()'),
    ('public','refresh_public_supply_feed()'),
    ('public','release_ai_analysis_job(uuid, text)'),
    ('public','release_deal_leg(uuid)'),
    ('public','release_inspector_payout(uuid)'),
    ('public','release_stripe_webhook_event(text, text)'),
    ('public','release_supplier_contract(uuid, integer, text)'),
    ('public','release_supplier_payout(uuid)'),
    ('public','request_account_deletion()'),
    ('public','request_named_disclosure(uuid, bigint)'),
    ('public','request_payout_advance(uuid, integer)'),
    ('public','request_price_revision(uuid, bigint, text, text)'),
    ('public','request_senior_review(uuid)'),
    ('public','request_withdrawal(bigint, text, text, uuid)'),
    ('public','resolve_job_dispute(uuid, text, text)'),
    ('public','respond_to_counter(uuid, text, bigint, text)'),
    ('public','restore_wallet_balance(uuid, bigint, text)'),
    ('public','reviews_populate_generalized()'),
    ('public','reviews_recompute_trigger()'),
    ('public','revoke_session(uuid)'),
    ('public','schedule_meeting(text, text, timestamp with time zone, uuid[], uuid, uuid, text, integer)'),
    ('public','seed_platform_owner(uuid)'),
    ('public','send_message(uuid, text, text, text, text)'),
    ('public','set_active_org(uuid)'),
    ('public','set_default_template(uuid)'),
    ('public','set_inspector_daily_limit(uuid, integer)'),
    ('public','settle_client_payment(uuid)'),
    ('public','sign_agreement(uuid, text, text, text)'),
    ('public','stripe_settle_named_disclosure(uuid, text, bigint, uuid)'),
    ('public','submit_quote(uuid, jsonb)'),
    ('public','supplier_has_quote_on_rfq(uuid, uuid)'),
    ('public','supplier_onboard(text, text[], jsonb, double precision, double precision, text, text)'),
    ('public','supplier_sign_contract(uuid, text, text)'),
    ('public','sweep_overdue_reports()'),
    ('public','tax_can_withdraw(uuid)'),
    ('public','tax_is_verified(uuid)'),
    ('public','tg_auto_issue_invoice_on_contract_executed()'),
    ('public','tg_credit_inspector_on_confirm()'),
    ('public','tool_eval(jsonb, jsonb)'),
    ('public','tool_has_pro_access(uuid)'),
    ('public','tool_validate_inputs(jsonb, jsonb)'),
    ('public','transfer_platform_owner(uuid, text)'),
    ('public','update_average_rating()'),
    ('public','update_average_rating_on_delete()'),
    ('public','upsert_tax_profile(text, text, text, text, timestamp with time zone)'),
    ('public','vault_store_tax_id(text, text, text, text)'),
    ('public','vca_claimed_address_text(uuid)'),
    ('public','vendor_document_record_anchor(uuid, text, text, text, bigint)'),
    ('public','vendor_document_seal(text, text, text, text, text, bigint, text, uuid)'),
    ('public','wallet_credit_topup(uuid, bigint, text, uuid, uuid)'),
    ('public','withdraw_revision(uuid, text)')
  ) AS t(grantee, sig) LOOP
    v_oid := to_regprocedure('public.' || r.sig);
    IF v_oid IS NOT NULL THEN
      EXECUTE format('REVOKE EXECUTE ON FUNCTION %s FROM %s',
                     v_oid::regprocedure::text,
                     CASE WHEN r.grantee = 'public' THEN 'PUBLIC' ELSE quote_ident(r.grantee) END);
    END IF;
  END LOOP;
END $fnrevoke$;

-- ── 4. Hardening beyond parity: PostGIS's reference table ──────────────────
--  spatial_ref_sys is NOT drift — the tested configuration grants anon the same
--  full write access, because that is PostGIS's own default. It is still wrong:
--  the table holds the coordinate-system definitions every geospatial query
--  resolves against, it has no RLS, and anon may TRUNCATE it. The application
--  only ever reads it. It is owned by supabase_admin, so the migration role may
--  not be able to revoke; that is not a reason to fail a security hotfix, so
--  the attempt is guarded and its outcome reported.
DO $srs$
BEGIN
  IF to_regclass('public.spatial_ref_sys') IS NULL THEN
    RAISE NOTICE 'spatial_ref_sys: absent (PostGIS not installed) — nothing to do';
    RETURN;
  END IF;
  REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON TABLE public.spatial_ref_sys
    FROM anon, authenticated, PUBLIC;
  RAISE NOTICE 'spatial_ref_sys: write access revoked from anon/authenticated (SELECT retained)';
EXCEPTION WHEN insufficient_privilege OR wrong_object_type THEN
  RAISE NOTICE 'spatial_ref_sys: not owned by the migration role — left as PostGIS installed it (pre-existing in every environment, not Production drift)';
END
$srs$;

-- ── 5. SELFTEST — the exposure this file exists to close ───────────────────
DO $verify$
DECLARE
  v_bad text;
  v_col text;
  v_n   int;
BEGIN
  -- (a) the RLS-less tables must be unwritable by anon
  SELECT string_agg(DISTINCT g.table_name, ', ' ORDER BY g.table_name) INTO v_bad
    FROM information_schema.role_table_grants g
   WHERE g.table_schema = 'public' AND g.grantee = 'anon'
     AND g.privilege_type IN ('INSERT','UPDATE','DELETE','TRUNCATE')
     --  spatial_ref_sys is handled above: PostGIS's own default, identical in
     --  the tested configuration, and not always revocable by this role.
     AND g.table_name IN ('assets','badges','error_logs','form_drafts','user_badges');
  IF v_bad IS NOT NULL THEN
    RAISE EXCEPTION 'HOTFIX FAILED: anon can still write RLS-less table(s): %', v_bad;
  END IF;

  -- (b) anon has no reach into jobs at all
  IF to_regclass('public.jobs') IS NOT NULL
     AND (has_table_privilege('anon','public.jobs','SELECT')
       OR has_table_privilege('anon','public.jobs','INSERT')
       OR has_table_privilege('anon','public.jobs','UPDATE')
       OR has_table_privilege('anon','public.jobs','DELETE')) THEN
    RAISE EXCEPTION 'HOTFIX FAILED: anon still holds a privilege on public.jobs';
  END IF;

  -- (c) GOLDEN_RULE_2 — buyer-only money columns unreadable by the marketplace
  IF to_regprocedure('public.nx_jobs_buyer_only_columns()') IS NOT NULL THEN
    FOREACH v_col IN ARRAY public.nx_jobs_buyer_only_columns() LOOP
      IF EXISTS (SELECT 1 FROM information_schema.columns
                  WHERE table_schema='public' AND table_name='jobs' AND column_name=v_col)
         AND has_column_privilege('authenticated','public.jobs',v_col,'SELECT') THEN
        RAISE EXCEPTION 'HOTFIX FAILED: authenticated may SELECT jobs.%', v_col;
      END IF;
    END LOOP;
  END IF;

  -- (d) the drift must not be able to grow back
  IF EXISTS (
    SELECT 1 FROM pg_default_acl d
      JOIN pg_namespace n ON n.oid = d.defaclnamespace
     WHERE n.nspname = 'public'
       AND d.defaclrole = 'postgres'::regrole
       AND array_to_string(d.defaclacl, ',') LIKE '%anon=%'
  ) THEN
    RAISE EXCEPTION 'HOTFIX FAILED: ALTER DEFAULT PRIVILEGES for postgres still grants anon in schema public';
  END IF;

  -- (e) internal derivations are not a public surface
  IF to_regprocedure('public.nx_qcp_scope_jobs(uuid,uuid)') IS NOT NULL
     AND has_function_privilege('authenticated','public.nx_qcp_scope_jobs(uuid,uuid)','EXECUTE') THEN
    RAISE EXCEPTION 'HOTFIX FAILED: nx_qcp_scope_jobs is reachable by authenticated';
  END IF;
  IF to_regprocedure('public.nx_schedule_conflicts_core(date,uuid,uuid,uuid)') IS NOT NULL
     AND has_function_privilege('authenticated','public.nx_schedule_conflicts_core(date,uuid,uuid,uuid)','EXECUTE') THEN
    RAISE EXCEPTION 'HOTFIX FAILED: the schedule-conflict core is executable by authenticated';
  END IF;

  -- (f) the application must NOT have been locked out. If the replay dropped
  --     these, this file is wrong and must fail loudly rather than ship a dead
  --     marketplace.
  IF to_regclass('public.applications') IS NOT NULL
     AND NOT has_table_privilege('authenticated','public.applications','SELECT') THEN
    RAISE EXCEPTION 'OVER-REVOKED: authenticated lost SELECT on applications';
  END IF;
  IF to_regclass('public.profiles') IS NOT NULL
     AND NOT has_table_privilege('authenticated','public.profiles','SELECT') THEN
    RAISE EXCEPTION 'OVER-REVOKED: authenticated lost SELECT on profiles';
  END IF;
  IF to_regclass('public.jobs') IS NOT NULL
     AND NOT has_column_privilege('authenticated','public.jobs','title','SELECT') THEN
    RAISE EXCEPTION 'OVER-REVOKED: authenticated lost SELECT on jobs.title';
  END IF;

  SELECT count(DISTINCT table_name) INTO v_n
    FROM information_schema.role_table_grants
   WHERE table_schema='public' AND grantee='anon'
     AND privilege_type IN ('INSERT','UPDATE','DELETE','TRUNCATE');
  RAISE NOTICE '════ privilege hotfix applied — anon write surface is now % table(s) ════', v_n;
END
$verify$;

COMMIT;
