'use client';
import { AiTable, StatusBadge, nf, dt, type Column } from '@/components/admin/ai-platform/kit';

interface Exp extends Record<string, unknown> {
  id: string; kind: string; version_tag: string | null; image_count: number; status: string; created_at: string;
}

const columns: Column<Exp>[] = [
  { key: 'kind', label: 'Format', render: (r) => <span className="rounded bg-white/5 px-2 py-0.5 text-[10px] font-semibold uppercase text-zinc-300">{r.kind}</span> },
  { key: 'version_tag', label: 'Version tag', render: (r) => <span className="font-mono text-xs">{r.version_tag ?? '—'}</span> },
  { key: 'image_count', label: 'Images', render: (r) => <span className="tabular-nums">{nf(r.image_count)}</span> },
  { key: 'status', label: 'Status', render: (r) => <StatusBadge value={r.status} /> },
  { key: 'created_at', label: 'Created', sortable: true, render: (r) => <span className="text-xs text-zinc-500">{dt(r.created_at)}</span> },
];

export default function ExportsPage() {
  return (
    <div>
      <p className="mb-3 text-sm text-zinc-400">Dataset export history. Packages (YOLO / COCO / ZIP / manifest / training‑package) are generated by the ExportService with a versioned, hash‑stable manifest. Building a new package requires a server/worker run; this view shows the truthful status of each and never fakes completion.</p>
      <AiTable<Exp>
        resource="exports"
        columns={columns}
        defaultSort="created_at"
        searchable={false}
        emptyTitle="No exports yet"
        emptyBody="Create a training package from the Training Center once a dataset version is frozen and its candidate set is approved."
      />
    </div>
  );
}
